package test;

import persistence.DAOFactory;
import persistence.UtilDao;
import persistence.dao.*;
import model.*;

public class TestDatabaseMain {

	public static void main(String[] args) {

		DAOFactory factory = DAOFactory.getDAOFactory(DAOFactory.POSTGRESQL);
		UtilDao util = factory.getUtilDAO();
		util.dropDatabase();
		util.createDatabase();
		
		AccountDao accountDao = factory.getAccountDAO();
		ChampionDao championDao = factory.getChampionDAO();
		ItemDao itemDao = factory.getItemDAO();
		RuneDao runeDao = factory.getRuneDAO();
		SpellDao spellDao = factory.getSpellDAO();
		SkillDao skillDao = factory.getSkillDAO();
		MiscDao miscDao = factory.getMiscDAO();

		Account account1 = new Account("Michele","michele123");
		Account account2 = new Account("Michelino","michele1234");
		Account account3 = new Account("Minchiele","michele12345");
		Account account4 = new Account("Robo", "ech");
		
		Champion champion1 = new Champion(1, "Annie");
		Champion champion2 = new Champion(2, "Olaf");
		Champion champion3 = new Champion(3, "Galio");
		Champion champion4 = new Champion(4, "Twisted Fate");
		Champion champion5 = new Champion(5, "Xin Zhao");
		Champion champion6 = new Champion(6, "Urgot");
		Champion champion7 = new Champion(7, "LeBlanc");
		Champion champion8 = new Champion(8, "Vladimir");
		Champion champion9 = new Champion(9, "Fiddlesticks");
		Champion champion10 = new Champion(10, "Kayle");
		Champion champion11 = new Champion(11, "Master Yi");
		Champion champion12 = new Champion(12, "Alistar");
		Champion champion13 = new Champion(13, "Ryze");
		Champion champion14 = new Champion(14, "Sion");
		Champion champion15 = new Champion(15, "Sivir");
		Champion champion16 = new Champion(16, "Soraka");
		Champion champion17 = new Champion(17, "Teemo");
		Champion champion18 = new Champion(18, "Tristana");
		Champion champion19 = new Champion(19, "Warwick");
		Champion champion20 = new Champion(20, "Nunu");
		Champion champion21 = new Champion(21, "Miss Fortune");
		Champion champion22 = new Champion(22, "Ashe");
		Champion champion23 = new Champion(23, "Tryndamere");
		Champion champion24 = new Champion(24, "Jax");
		Champion champion25 = new Champion(25, "Morgana");
		Champion champion26 = new Champion(26, "Zilean");
		Champion champion27 = new Champion(27, "Singed");
		Champion champion28 = new Champion(28, "Evelynn");
		Champion champion29 = new Champion(29, "Twitch");
		Champion champion30 = new Champion(30, "Karthus");
		Champion champion31 = new Champion(31, "Cho'Gath");
		Champion champion32 = new Champion(32, "Amumu");
		Champion champion33 = new Champion(33, "Rammus");
		Champion champion34 = new Champion(34, "Anivia");
		Champion champion35 = new Champion(35, "Shaco");
		Champion champion36 = new Champion(36, "Dr.Mundo");
		Champion champion37 = new Champion(37, "Sona");
		Champion champion38 = new Champion(38, "Kassadin");
		Champion champion39 = new Champion(39, "Irelia");
		Champion champion40 = new Champion(40, "Janna");
		Champion champion41 = new Champion(41, "Gangplank");
		Champion champion42 = new Champion(42, "Corki");
		Champion champion43 = new Champion(43, "Karma");
		Champion champion44 = new Champion(44, "Taric");
		Champion champion45 = new Champion(45, "Veigar");
		Champion champion46 = new Champion(48, "Trundle");
		Champion champion47 = new Champion(50, "Swain");
		Champion champion48 = new Champion(51, "Caitlyn");
		Champion champion49 = new Champion(53, "Blitzcrank");
		Champion champion50 = new Champion(54, "Malphite");
		Champion champion51 = new Champion(55, "Katarina");
		Champion champion52 = new Champion(56, "Nocturne");
		Champion champion53 = new Champion(57, "Maokai");
		Champion champion54 = new Champion(58, "Renekton");
		Champion champion55 = new Champion(59, "Jarvan IV");
		Champion champion56 = new Champion(60, "Elise");
		Champion champion57 = new Champion(61, "Orianna");
		Champion champion58 = new Champion(62, "Wukong");
		Champion champion59 = new Champion(63, "Brand");
		Champion champion60 = new Champion(64, "Lee Sin");
		Champion champion61 = new Champion(67, "Vayne");
		Champion champion62 = new Champion(68, "Rumble");
		Champion champion63 = new Champion(69, "Cassiopeia");
		Champion champion64 = new Champion(72, "Skarner");
		Champion champion65 = new Champion(74, "Heimerdinger");
		Champion champion66 = new Champion(75, "Nasus");
		Champion champion67 = new Champion(76, "Nidalee");
		Champion champion68 = new Champion(77, "Udyr");
		Champion champion69 = new Champion(78, "Poppy");
		Champion champion70 = new Champion(79, "Gragas");
		Champion champion71 = new Champion(80, "Pantheon");
		Champion champion72 = new Champion(81, "Ezreal");
		Champion champion73 = new Champion(82, "Mordekaiser");
		Champion champion74 = new Champion(83, "Yorick");
		Champion champion75 = new Champion(84, "Akali");
		Champion champion76 = new Champion(85, "Kennen");
		Champion champion77 = new Champion(86, "Garen");
		Champion champion78 = new Champion(89, "Leona");
		Champion champion79 = new Champion(90, "Malzahar");
		Champion champion80 = new Champion(91, "Talon");
		Champion champion81 = new Champion(92, "Riven");
		Champion champion82 = new Champion(96, "Kog'Maw");
		Champion champion83 = new Champion(98, "Shen");
		Champion champion84 = new Champion(99, "Lux");
		Champion champion85 = new Champion(101, "Xerath");
		Champion champion86 = new Champion(102, "Shyvana");
		Champion champion87 = new Champion(103, "Ahri");
		Champion champion88 = new Champion(104, "Graves");
		Champion champion89 = new Champion(105, "Fizz");
		Champion champion90 = new Champion(106, "Volibear");
		Champion champion91 = new Champion(107, "Rengar");
		Champion champion92 = new Champion(110, "Varus");
		Champion champion93 = new Champion(111, "Nautilus");
		Champion champion94 = new Champion(112, "Viktor");
		Champion champion95 = new Champion(113, "Sejuani");
		Champion champion96 = new Champion(114, "Fiora");
		Champion champion97 = new Champion(115, "Ziggs");
		Champion champion98 = new Champion(117, "Lulu");
		Champion champion99 = new Champion(119, "Draven");
		Champion champion100 = new Champion(120, "Hecarim");
		Champion champion101 = new Champion(121, "Kha'Zix");
		Champion champion102 = new Champion(122, "Darius");
		Champion champion103 = new Champion(126, "Jayce");
		Champion champion104 = new Champion(127, "Lissandra");
		Champion champion105 = new Champion(131, "Diana");
		Champion champion106 = new Champion(133, "Quinn");
		Champion champion107 = new Champion(134, "Syndra");
		Champion champion108 = new Champion(136, "Aurelion Sol");
		Champion champion109 = new Champion(141, "Kayn");
		Champion champion110 = new Champion(142, "Zoe");
		Champion champion111 = new Champion(143, "Zyra");
		Champion champion112 = new Champion(150, "Gnar");
		Champion champion113 = new Champion(154, "Zac");
		Champion champion114 = new Champion(157, "Yasuo");
		Champion champion115 = new Champion(161, "Vel'Koz");
		Champion champion116 = new Champion(163, "Taliyah");
		Champion champion117 = new Champion(164, "Camille");
		Champion champion118 = new Champion(201, "Braum");
		Champion champion119 = new Champion(202, "Jhin");
		Champion champion120 = new Champion(203, "Kindred");
		Champion champion121 = new Champion(222, "Jinx");
		Champion champion122 = new Champion(223, "Tahm Kench");
		Champion champion123 = new Champion(236, "Lucian");
		Champion champion124 = new Champion(238, "Zed");
		Champion champion125 = new Champion(240, "Kled");
		Champion champion126 = new Champion(245, "Ekko");
		Champion champion127 = new Champion(254, "Vi");
		Champion champion128 = new Champion(266, "Aatrox");
		Champion champion129 = new Champion(267, "Nami");
		Champion champion130 = new Champion(268, "Azir");
		Champion champion131 = new Champion(412, "Thresh");
		Champion champion132 = new Champion(420, "IllaoI");
		Champion champion133 = new Champion(421, "Rek'Sai");
		Champion champion134 = new Champion(427, "Ivern");
		Champion champion135 = new Champion(429, "Kalista");
		Champion champion136 = new Champion(432, "Bard");
		Champion champion137 = new Champion(497, "Rakan");
		Champion champion138 = new Champion(498, "Xayah");
		Champion champion139 = new Champion(516, "Ornn");

		
		Item item1= new Item(1001, "Stivali della velocità");
		Item item2= new Item(1004, "Amuleto della fata");
		Item item3= new Item(1006, "Perla del rinvigorimento");
		Item item4= new Item(1011, "Cintura del gigante");
		Item item5= new Item(1018, "Cappa dell'agilità");
		Item item6= new Item(1026, "Bacchetta distruttiva");
		Item item7= new Item(1027, "Zaffiro di cristallo");
		Item item8= new Item(1028, "Rubino di cristallo");
		Item item9= new Item(1029, "Armatura di stoffa");
		Item item10= new Item(1031, "Cotta di maglia");
		Item item11= new Item(1033, "Cappa anti-magia");
		Item item12= new Item(1036, "Spada lunga");
		Item item13= new Item(1037, "Piccone");
		Item item14= new Item(1038, "M.C. Spada");
		Item item15= new Item(1039, "Talismano del cacciatore");
		Item item16= new Item(1041, "Machete del cacciatore");
		Item item17= new Item(1042, "Daga");
		Item item18= new Item(1043, "Arco ricurvo");
		Item item19= new Item(1051, "Guanti da mischia");
		Item item20= new Item(1052, "Tomo del potenziamento");
		Item item21= new Item(1053, "Scettro vampirico");
		Item item22= new Item(1054, "Scudo di Doran");
		Item item23= new Item(1055, "Lama di Doran");
		Item item24= new Item(1056, "Anello di Doran");
		Item item25= new Item(1057, "Mantello di Negatron");
		Item item26= new Item(1058, "Bastone colossale");
		Item item27= new Item(1082, "Sigillo oscuro");
		Item item28= new Item(1083, "Mietitore");
		Item item29= new Item(1400, "Gemma del Guerriero");
		Item item30= new Item(1401, "Gemma del Colosso cinereo");
		Item item31= new Item(1402, "Gemma degli Echi delle rune");
		Item item32= new Item(1408, "Gemma del Guerriero");
		Item item33= new Item(1409, "Gemma del Colosso cinereo");
		Item item34= new Item(1410, "Gemma degli Echi delle rune");
		Item item35= new Item(1412, "Gemma del Guerriero");
		Item item36= new Item(1413, "Gemma del Colosso cinereo");
		Item item37= new Item(1414, "Gemma degli Echi delle rune");
		Item item38= new Item(1416, "Gemma degli Artigli rossi");
		Item item39= new Item(1418, "Gemma degli Artigli rossi");
		Item item40= new Item(1419, "Gemma degli Artigli rossi");
		Item item41= new Item(2003, "Pozione di salute");
		Item item42= new Item(2004, "Pozione di mana");
		Item item43= new Item(2009, "Biscotto della giovinezza");
		Item item44= new Item(2010, "Biscotto eterno della volontà");
		Item item45= new Item(2011, "Elisir di abilità");
		Item item46= new Item(2012, "Biscotto della giovinezza saccheggiato");
		Item item47= new Item(2013, "Estratto dell'oracolo saccheggiato");
		Item item48= new Item(2015, "Scheggia di Kircheis");
		Item item49= new Item(2031, "Pozione ricaricabile");
		Item item50= new Item(2032, "Pozione del cacciatore");
		Item item51= new Item(2033, "Pozione della corruzione");
		Item item52= new Item(2045, "Rubino della visione");
		Item item53= new Item(2047, "Estratto dell'oracolo");
		Item item54= new Item(2049, "Pietra della visione");
		Item item55= new Item(2050, "Lume dell'esploratore");
		Item item56= new Item(2051, "Corno del guardiano");
		Item item57= new Item(2052, "Poro-Snax");
		Item item58= new Item(2053, "Cappa rapace");
		Item item59= new Item(2054, "Poro-Snax dietetico");
		Item item60= new Item(2055, "Lume di controllo");
		Item item61= new Item(2056, "Lume invisibile rubato");
		Item item62= new Item(2057, "Lume di lungavisione sbirciante");
		Item item63= new Item(2058, "Elisir da viaggio del ferro");
		Item item64= new Item(2059, "Elisir da viaggio della stregoneria");
		Item item65= new Item(2060, "Elisir da viaggio dell'ira");
		Item item66= new Item(2061, "Pozione di salute rubata");
		Item item67= new Item(2062, "Pozione del solitario rubata");
		Item item68= new Item(2138, "Elisir del ferro");
		Item item69= new Item(2139, "Elisir della stregoneria");
		Item item70= new Item(2140, "Elisir dell'ira");
		Item item71= new Item(2301, "Occhio degli osservatori");
		Item item72= new Item(2302, "Occhio dell'oasi");
		Item item73= new Item(2303, "Occhio dell'equinozio");
		Item item74= new Item(2319, "Scaltro sacco d'oro");
		Item item75= new Item(2403, "Smaterializzatore");
		Item item76= new Item(2419, "Trasformazione in Cronografo");
		Item item77= new Item(2420, "Cronografo");
		Item item78= new Item(2421, "Cronografo rotto");
		Item item79= new Item(2422, "Stivali lievemente magici");
		Item item80= new Item(2423, "Cronografo");
		Item item81= new Item(2424, "Cronografo rotto");
		Item item82= new Item(3001, "Maschera dell'abisso");
		Item item83= new Item(3003, "Scettro dell'arcangelo");
		Item item84= new Item(3004, "Manamune");
		Item item85= new Item(3006, "Gambali del berserker");
		Item item86= new Item(3007, "Scettro dell'arcangelo (Carica rapida)");
		Item item87= new Item(3008, "Manamume (Carica rapida)");
		Item item88= new Item(3009, "Stivali della rapidità");
		Item item89= new Item(3010, "Ametista degli eoni");
		Item item90= new Item(3020, "Calzari del mago");
		Item item91= new Item(3022, "Martello ghiacciato");
		Item item92= new Item(3024, "Velo glaciale");
		Item item93= new Item(3025, "Guanto del gelo");
		Item item94= new Item(3026, "Angelo custode");
		Item item95= new Item(3027, "Bastone secolare");
		Item item96= new Item(3028, "Calice dell'armonia");
		Item item97= new Item(3029, "Bastone secolare (Carica rapida)");
		Item item98= new Item(3030, "Hextech GLP-800");
		Item item99= new Item(3031, "Frammento d'infinito");
		Item item100= new Item(3033, "Memento mori");
		Item item101= new Item(3034, "Uccisore di giganti");
		Item item102= new Item(3035, "Sussurro fatale");
		Item item103= new Item(3036, "Saluti di Lord Dominik");
		Item item104= new Item(3040, "Abbraccio serafico");
		Item item105= new Item(3041, "Tomo Mejai ruba-anime");
		Item item106= new Item(3042, "Muramana");
		Item item107= new Item(3043, "Muramana");
		Item item108= new Item(3044, "Flagello");
		Item item109= new Item(3046, "Danzatore fantasma");
		Item item110= new Item(3047, "Calzari del ninja");
		Item item111= new Item(3048, "Abbraccio serafico");
		Item item112= new Item(3050, "Convergenza di Zeke");
		Item item113= new Item(3052, "Pugno di Jaurim");
		Item item114= new Item(3053, "Pegno di Sterak");
		Item item115= new Item(3056, "Spaccaresistenze");
		Item item116= new Item(3057, "Fulgore");
		Item item117= new Item(3060, "Stendardo del comando");
		Item item118= new Item(3065, "Corazza spirituale");
		Item item119= new Item(3067, "Gemma infuocata");
		Item item120= new Item(3068, "Mantello del Sole");
		Item item121= new Item(3069, "Talismano dell'ascensione");
		Item item122= new Item(3070, "Lacrime della dea");
		Item item123= new Item(3071, "Mannaia oscura");
		Item item124= new Item(3072, "La Bramasangue");
		Item item125= new Item(3073, "Lacrima della dea (Carica rapida)");
		Item item126= new Item(3074, "Idra famelica");
		Item item127= new Item(3075, "Corazza spinata");
		Item item128= new Item(3076, "Corpetto di rovi");
		Item item129= new Item(3077, "Tiamat");
		Item item130= new Item(3078, "Virtù della Triade");
		Item item131= new Item(3082, "Armatura del custode");
		Item item132= new Item(3083, "Armatura di Warmog");
		Item item133= new Item(3084, "Cotta di maglia del signore supremo");
		Item item134= new Item(3085, "Uragano di Runaan");
		Item item135= new Item(3086, "Fervore");
		Item item136= new Item(3087, "Pugnale di Statikk");
		Item item137= new Item(3089, "Copricapo di Rabadon");
		Item item138= new Item(3090, "Copricapo di Wooglet");
		Item item139= new Item(3091, "Speranza perduta");
		Item item140= new Item(3092, "Volere della regina dei ghiacci");
		Item item141= new Item(3094, "Archibugio a ripetizione");
		Item item142= new Item(3096, "Medaglione del nomade");
		Item item143= new Item(3097, "Difesa di Targon");
		Item item144= new Item(3098, "Zanna di ghiaccio");
		Item item145= new Item(3100, "Terrore dei lich");
		Item item146= new Item(3101, "Pungolo");
		Item item147= new Item(3102, "Velo della Banshee");
		Item item148= new Item(3104, "Distruttore di Lord Van Damm");
		Item item149= new Item(3105, "Egida della legione");
		Item item150= new Item(3107, "Redenzione");
		Item item151= new Item(3108, "Codice del diavolo");
		Item item152= new Item(3109, "Voto del cavaliere");
		Item item153= new Item(3110, "Fulcro dei geli");
		Item item154= new Item(3111, "Calzari di mercurio");
		Item item155= new Item(3112, "Globo del guardiano");
		Item item156= new Item(3113, "Fiamma eterea");
		Item item157= new Item(3114, "Idolo proibito");
		Item item158= new Item(3115, "Dente di Nashor");
		Item item159= new Item(3116, "Scettro di cristallo di Rylai");
		Item item160= new Item(3117, "Stivali della mobilità");
		Item item161= new Item(3122, "Accetta malefica");
		Item item162= new Item(3123, "Chiamata del carnefice");
		Item item163= new Item(3124, "Furia di Guinsoo");
		Item item164= new Item(3133, "Martello da guerra di Caulfield");
		Item item165= new Item(3134, "Lungo pugnale seghettato");
		Item item166= new Item(3135, "Bastone del Vuoto");
		Item item167= new Item(3136, "Maschera stregata");
		Item item168= new Item(3137, "lama del derviscio");
		Item item169= new Item(3139, "Scimitarra di Mercurio");
		Item item170= new Item(3140, "Fascia d'argento vivo");
		Item item171= new Item(3142, "Lama di Youmuu");
		Item item172= new Item(3143, "Orgoglio di Randuin");
		Item item173= new Item(3144, "Sciabola di Bilgewater");
		Item item174= new Item(3145, "Revolver Hextech");
		Item item175= new Item(3146, "Pistola a lame hextech");
		Item item176= new Item(3147, "Lama crepuscolare di Draktharr");
		Item item177= new Item(3151, "Tormento di Liandry");
		Item item178= new Item(3152, "Protocintura hextech 01");
		Item item179= new Item(3153, "Lama del re in rovina");
		Item item180= new Item(3155, "Mangiamagia");
		Item item181= new Item(3156, "Fauci di Malmortius");
		Item item182= new Item(3157, "Clessidra di Zhonya");
		Item item183= new Item(3158, "Stivali dell'acume di Ionia");
		Item item184= new Item(3165, "Morellonomicon");
		Item item185= new Item(3170, "Lama della Luna");
		Item item186= new Item(3174, "Empio Graal di Athene");
		Item item187= new Item(3175, "Testa di Kha'Zix");
		Item item188= new Item(3181, "Lama sanguigna");
		Item item189= new Item(3184, "Martello del guardiano");
		Item item190= new Item(3185, "Il portatore di luce");
		Item item191= new Item(3187, "Occhio arcano");
		Item item192= new Item(3190, "Medaglione dei Solari di ferro");
		Item item193= new Item(3191, "Parabraccia del cercatore");
		Item item194= new Item(3193, "Lastrapietra del gargoyle");
		Item item195= new Item(3194, "Elmo adattivo");
		Item item196= new Item(3196, "Nucleo incantato mk-1");
		Item item197= new Item(3197, "Nucleo incantato mk-2");
		Item item198= new Item(3198, "Nucleo incantato perfetto");
		Item item199= new Item(3200, "Nucleo incantato prototipo");
		Item item200= new Item(3211, "Capuccio spettrale");
		Item item201= new Item(3222, "Crogiolo di Mikael");
		Item item202= new Item(3252, "Lungo pugnale del bracconiere");
		Item item203= new Item(3285, "Eco di Luden");
		Item item204= new Item(3301, "Moneta antica");
		Item item205= new Item(3302, "Scudo reliquia");
		Item item206= new Item(3303, "Vantaggio del mago ladro");
		Item item207= new Item(3340, "Totem guardiano (Trinket)");
		Item item208= new Item(3341, "Lente mobile (Trinket)");
		Item item209= new Item(3345, "Ancora spirituale (Trinket)");
		Item item210= new Item(3348, "Occhio arcano");
		Item item211= new Item(3361, "Totem invisibile maggiore (Trinket)");
		Item item212= new Item(3362, "Totem della visione maggiore (Trinket)");
		Item item213= new Item(3363, "Modifica lungavisione");
		Item item214= new Item(3364, "Modifica oracolo");
		Item item215= new Item(3371, "Frammento incandescente");
		Item item216= new Item(3373, "Mantello della forgia");
		Item item217= new Item(3374, "Corona funebre di Rabadon");
		Item item218= new Item(3379, "Maschera infernale");
		Item item219= new Item(3380, "Mannaia di ossidiana");
		Item item220= new Item(3382, "Salvezza");
		Item item221= new Item(3383, "Diadema dei Solari di ferro");
		Item item222= new Item(3384, "Fusione della trinità");
		Item item223= new Item(3385, "Corona di Wooglet");
		Item item224= new Item(3386, "Paradosso di Zhonya");
		Item item225= new Item(3401, "Volto della montagna");
		Item item226= new Item(3410, "Testa di Kha'Zix");
		Item item227= new Item(3416, "Testa di Kha'Zix");
		Item item228= new Item(3422, "Testa di Kha'Zix");
		Item item229= new Item(3455, "Testa di Kha'Zix");
		Item item230= new Item(3460, "Trascendenza dorata");
		Item item231= new Item(3461, "Trascendenza dorata (disattivata)");
		Item item232= new Item(3462, "Pietra divinatoria (trinket)");
		Item item233= new Item(3504, "Incensiere ardente");
		Item item234= new Item(3508, "Predatore d'essenza");
		Item item235= new Item(3512, "Portale Zz'Rot");
		Item item236= new Item(3513, "Occhio del Messaggero");
		Item item237= new Item(3599, "Lancia oscura");
		Item item238= new Item(3630, "Teletrasporto d'assedio");
		Item item239= new Item(3631, "Ballista d'assedio");
		Item item240= new Item(3633, "Teletrasporto d'assedio");
		Item item241= new Item(3634, "Torre: Raggio della rovina");
		Item item242= new Item(3635, "Piattaforma di teletrasporto");
		Item item243= new Item(3636, "Torre: Bastione della tempesta");
		Item item244= new Item(3637, "Assedio al nexus, Slot arma d'assedio");
		Item item245= new Item(3640, "Zona Flash");
		Item item246= new Item(3641, "Stendardo dell'avanguardia");
		Item item247= new Item(3642, "Rimborso assedio");
		Item item248= new Item(3643, "Campo entropico");
		Item item249= new Item(3645, "Pietra divinatoria (trinket)");
		Item item250= new Item(3647, "Totem scudo");
		Item item251= new Item(3649, "Illuminatore d'assedio");
		Item item252= new Item(3671, "Gemma del Guerriero");
		Item item253= new Item(3672, "Gemma del Colosso cinereo");
		Item item254= new Item(3673, "Gemma degli Echi delle rune");
		Item item255= new Item(3675, "Gemma degli Artigli rossi");
		Item item256= new Item(3680, "Snax glassato");
		Item item257= new Item(3681, "Snax superpiccante");
		Item item258= new Item(3682, "Snax espresso");
		Item item259= new Item(3683, "Pacchetto Snax arcobaleno!");
		Item item260= new Item(3690, "Catena cosmica");
		Item item261= new Item(3691, "Lanterna della Singolarità");
		Item item262= new Item(3692, "Falce della Materia oscura");
		Item item263= new Item(3693, "Stivali gravitazionali");
		Item item264= new Item(3694, "Mantello stellare");
		Item item265= new Item(3695, "Sigillo della Stella Oscura");
		Item item266= new Item(3706, "Lama del cacciatore");
		Item item267= new Item(3711, "Coltello del segugio");
		Item item268= new Item(3715, "Sciabola del soldato");
		Item item269= new Item(3742, "Corazza dell'uomo morto");
		Item item270= new Item(3748, "Idra titanica");
		Item item271= new Item(3751, "Tizzone di Bami");
		Item item272= new Item(3800, "Gloria del giusto");
		Item item273= new Item(3801, "Bracciale cristallino");
		Item item274= new Item(3802, "Capitolo perduto");
		Item item275= new Item(3812, "Danza della Morte");
		Item item276= new Item(3814, "Fine della notte");
		Item item277= new Item(3901, "Fuoco a volontà");
		Item item278= new Item(3902, "Figlia della Morte");
		Item item279= new Item(3903, "Morale alto");
		
		
		
		Rune rune1= new Rune(8000, "Precisione");
		Rune rune2= new Rune(8100, "Dominazione");
		Rune rune3= new Rune(8200, "Stregoneria");
		Rune rune4= new Rune(8300, "Ispirazione");
		Rune rune5= new Rune(8400, "Determinazione");
		Rune rune6= new Rune(7000, "Template");
		Rune rune7= new Rune(8005, "Attacco sostenuto");
		Rune rune8= new Rune(8008, "Tempo letale");
		Rune rune9= new Rune(8009, "Presenza di spirito");
		Rune rune10= new Rune(8014, "Colpo di grazia");
		Rune rune11= new Rune(8017, "Colpo profondo");
		Rune rune12= new Rune(8021, "Piede lesto");
		Rune rune13= new Rune(8105, "Cacciatore implacabile");
		Rune rune14= new Rune(8112, "Elettroshock");
		Rune rune15= new Rune(8120, "Poro Fantasma");
		Rune rune16= new Rune(8124, "Predatore");
		Rune rune17= new Rune(8126, "Colpo basso");
		Rune rune18= new Rune(8128, "Raccolto oscuro");
		Rune rune19= new Rune(8134, "Ingegnoso cacciatore");
		Rune rune20= new Rune(8135, "Cacciatore famelico");
		Rune rune21= new Rune(8136, "Lume zombi");
		Rune rune22= new Rune(8138, "Collezione di bulbi");
		Rune rune23= new Rune(8139, "Assaggio di sangue");
		Rune rune24= new Rune(8143, "Impatto improvviso");
		Rune rune25= new Rune(8210, "Trascendenza");
		Rune rune26= new Rune(8214, "Evoca Aery");
		Rune rune27= new Rune(8224, "Sfera dell'annullamento");
		Rune rune28= new Rune(8226, "Fascia del flusso");
		Rune rune29= new Rune(8229, "Cometa arcana");
		Rune rune30= new Rune(8230, "Scatto fasico");
		Rune rune31= new Rune(8232, "Camminare sull'acqua");
		Rune rune32= new Rune(8233, "Concentrazione assoluta");
		Rune rune33= new Rune(8234, "Celerità");
		Rune rune34= new Rune(8236, "Tempesta incombente");
		Rune rune35= new Rune(8237, "Bruciare");
		Rune rune36= new Rune(8242, "Risoluto");
		Rune rune37= new Rune(8243, "Il cappello supremo");
		Rune rune38= new Rune(8299, "L'ultima sfida");
		Rune rune39= new Rune(8304, "Calzature magiche");
		Rune rune40= new Rune(8306, "Marchingegno Heflash");
		Rune rune41= new Rune(8313, "Tempismo perfetto");
		Rune rune42= new Rune(8316, "Smaterializzatore");
		Rune rune43= new Rune(8321, "Mercato del futuro");
		Rune rune44= new Rune(8326, "Libro incantesimi non sigillato");
		Rune rune45= new Rune(8339, "Corpo celeste");
		Rune rune46= new Rune(8345, "Consegna biscotti");
		Rune rune47= new Rune(8347, "Intuito cosmico");
		Rune rune48= new Rune(8351, "Potenziamento glaciale");
		Rune rune49= new Rune(8359, "Cleptomanzia");
		Rune rune50= new Rune(8410, "Velocità di avvicinamento");
		Rune rune51= new Rune(8429, "Preparazione fisica");
		Rune rune52= new Rune(8430, "Pelle di ferro");
		Rune rune53= new Rune(8435, "Guscio a specchio");
		Rune rune54= new Rune(8437, "Presa dell'immortale");
		Rune rune55= new Rune(8439, "Scossa di assestamento");
		Rune rune56= new Rune(8444, "Secondo fiato");
		Rune rune57= new Rune(8446, "Demolire");
		Rune rune58= new Rune(8451, "Crescita eccessiva");
		Rune rune59= new Rune(8453, "Rivitalizzare");
		Rune rune60= new Rune(8465, "Sorvegliante");
		Rune rune61= new Rune(9101, "Sovraguarigione");
		Rune rune62= new Rune(9103, "Leggenda: Stirpe");
		Rune rune63= new Rune(9104, "Leggenda: Alacrità");
		Rune rune64= new Rune(9105, "Leggenda: Tenacità");
		Rune rune65= new Rune(9111, "Trionfo");
		Rune rune66= new Rune(8463, "Fonte vitale");
		
		Spell spell1=new Spell(34, "Assedio al nexus: Slot arma d'assedio");
		Spell spell2=new Spell(12, "Teletrasporto");
		Spell spell3=new Spell(33, "Assedio al nexus: Slot arma d'assedio");
		Spell spell4=new Spell(3, "Sfinimento");
		Spell spell5=new Spell(21, "Barriera");
		Spell spell6=new Spell(13, "Chiarezza");
		Spell spell7=new Spell(39, "Ultra marchio (lanciato velocemente)");
		Spell spell8=new Spell(4, "Flash");
		Spell spell9=new Spell(32, "Marchio");
		Spell spell10=new Spell(14, "Ustione");
		Spell spell11=new Spell(36, "Incantesimi dell'evocatore disabilitati");
		Spell spell12=new Spell(35, "Incantesimi dell'evocatore disabilitati");
		Spell spell13=new Spell(30, "Teleporo!");
		Spell spell14=new Spell(6, "Spettralità");
		Spell spell15=new Spell(-1, "Ultra scatto (velocissimo!)");
		Spell spell16=new Spell(7, "Guarigione");
		Spell spell17=new Spell(31, "Lancio del Poro");
		Spell spell18=new Spell(1, "Purificazione");
		Spell spell19=new Spell(11, "Punizione");
		
		Skill skill1= new Skill (1, "Test");
	
		Misc misc1= new Misc (1, "test");
		
		
		accountDao.save(account1);
		accountDao.save(account2);
		accountDao.save(account3);
		accountDao.save(account4);
		
		championDao.save(champion1);
		championDao.save(champion2);
		championDao.save(champion3);
		championDao.save(champion4);
		championDao.save(champion5);
		championDao.save(champion6);
		championDao.save(champion7);
		championDao.save(champion8);
		championDao.save(champion9);
		championDao.save(champion10);
		championDao.save(champion11);
		championDao.save(champion12);
		championDao.save(champion13);
		championDao.save(champion14);
		championDao.save(champion15);
		championDao.save(champion16);
		championDao.save(champion17);
		championDao.save(champion18);
		championDao.save(champion19);
		championDao.save(champion20);
		championDao.save(champion21);
		championDao.save(champion22);
		championDao.save(champion23);
		championDao.save(champion24);
		championDao.save(champion25);
		championDao.save(champion26);
		championDao.save(champion27);
		championDao.save(champion28);
		championDao.save(champion29);
		championDao.save(champion30);
		championDao.save(champion31);
		championDao.save(champion32);
		championDao.save(champion33);
		championDao.save(champion34);
		championDao.save(champion35);
		championDao.save(champion36);
		championDao.save(champion37);
		championDao.save(champion38);
		championDao.save(champion39);
		championDao.save(champion40);
		championDao.save(champion41);
		championDao.save(champion42);
		championDao.save(champion43);
		championDao.save(champion44);
		championDao.save(champion45);
		championDao.save(champion46);
		championDao.save(champion47);
		championDao.save(champion48);
		championDao.save(champion49);
		championDao.save(champion50);
		championDao.save(champion51);
		championDao.save(champion52);
		championDao.save(champion53);
		championDao.save(champion54);
		championDao.save(champion55);
		championDao.save(champion56);
		championDao.save(champion57);
		championDao.save(champion58);
		championDao.save(champion59);
		championDao.save(champion60);
		championDao.save(champion61);
		championDao.save(champion62);
		championDao.save(champion63);
		championDao.save(champion64);
		championDao.save(champion65);
		championDao.save(champion66);
		championDao.save(champion67);
		championDao.save(champion68);
		championDao.save(champion69);
		championDao.save(champion70);
		championDao.save(champion71);
		championDao.save(champion72);
		championDao.save(champion73);
		championDao.save(champion74);
		championDao.save(champion75);
		championDao.save(champion76);
		championDao.save(champion77);
		championDao.save(champion78);
		championDao.save(champion79);
		championDao.save(champion80);
		championDao.save(champion81);
		championDao.save(champion82);
		championDao.save(champion83);
		championDao.save(champion84);
		championDao.save(champion85);
		championDao.save(champion86);
		championDao.save(champion87);
		championDao.save(champion88);
		championDao.save(champion89);
		championDao.save(champion90);
		championDao.save(champion91);
		championDao.save(champion92);
		championDao.save(champion93);
		championDao.save(champion94);
		championDao.save(champion95);
		championDao.save(champion96);
		championDao.save(champion97);
		championDao.save(champion98);
		championDao.save(champion99);
		championDao.save(champion100);
		championDao.save(champion101);
		championDao.save(champion102);
		championDao.save(champion103);
		championDao.save(champion104);
		championDao.save(champion105);
		championDao.save(champion106);
		championDao.save(champion107);
		championDao.save(champion108);
		championDao.save(champion109);
		championDao.save(champion110);
		championDao.save(champion111);
		championDao.save(champion112);
		championDao.save(champion113);
		championDao.save(champion114);
		championDao.save(champion115);
		championDao.save(champion116);
		championDao.save(champion117);
		championDao.save(champion118);
		championDao.save(champion119);
		championDao.save(champion120);
		championDao.save(champion121);
		championDao.save(champion122);
		championDao.save(champion123);
		championDao.save(champion124);
		championDao.save(champion125);
		championDao.save(champion126);
		championDao.save(champion127);
		championDao.save(champion128);
		championDao.save(champion129);
		championDao.save(champion130);
		championDao.save(champion131);
		championDao.save(champion132);
		championDao.save(champion133);
		championDao.save(champion134);
		championDao.save(champion135);
		championDao.save(champion136);
		championDao.save(champion137);
		championDao.save(champion138);
		championDao.save(champion139);
		
		itemDao.save(item1);
		itemDao.save(item2);
		itemDao.save(item3);
		itemDao.save(item4);
		itemDao.save(item5);
		itemDao.save(item6);
		itemDao.save(item7);
		itemDao.save(item8);
		itemDao.save(item9);
		itemDao.save(item10);
		itemDao.save(item11);
		itemDao.save(item12);
		itemDao.save(item13);
		itemDao.save(item14);
		itemDao.save(item15);
		itemDao.save(item16);
		itemDao.save(item17);
		itemDao.save(item18);
		itemDao.save(item19);
		itemDao.save(item20);
		itemDao.save(item21);
		itemDao.save(item22);
		itemDao.save(item23);
		itemDao.save(item24);
		itemDao.save(item25);
		itemDao.save(item26);
		itemDao.save(item27);
		itemDao.save(item28);
		itemDao.save(item29);
		itemDao.save(item30);
		itemDao.save(item31);
		itemDao.save(item32);
		itemDao.save(item33);
		itemDao.save(item34);
		itemDao.save(item35);
		itemDao.save(item36);
		itemDao.save(item37);
		itemDao.save(item38);
		itemDao.save(item39);
		itemDao.save(item40);
		itemDao.save(item41);
		itemDao.save(item42);
		itemDao.save(item43);
		itemDao.save(item44);
		itemDao.save(item45);
		itemDao.save(item46);
		itemDao.save(item47);
		itemDao.save(item48);
		itemDao.save(item49);
		itemDao.save(item50);
		itemDao.save(item51);
		itemDao.save(item52);
		itemDao.save(item53);
		itemDao.save(item54);
		itemDao.save(item55);
		itemDao.save(item56);
		itemDao.save(item57);
		itemDao.save(item58);
		itemDao.save(item59);
		itemDao.save(item60);
		itemDao.save(item61);
		itemDao.save(item62);
		itemDao.save(item63);
		itemDao.save(item64);
		itemDao.save(item65);
		itemDao.save(item66);
		itemDao.save(item67);
		itemDao.save(item68);
		itemDao.save(item69);
		itemDao.save(item70);
		itemDao.save(item71);
		itemDao.save(item72);
		itemDao.save(item73);
		itemDao.save(item74);
		itemDao.save(item75);
		itemDao.save(item76);
		itemDao.save(item77);
		itemDao.save(item78);
		itemDao.save(item79);
		itemDao.save(item80);
		itemDao.save(item81);
		itemDao.save(item82);
		itemDao.save(item83);
		itemDao.save(item84);
		itemDao.save(item85);
		itemDao.save(item86);
		itemDao.save(item87);
		itemDao.save(item88);
		itemDao.save(item89);
		itemDao.save(item90);
		itemDao.save(item91);
		itemDao.save(item92);
		itemDao.save(item93);
		itemDao.save(item94);
		itemDao.save(item95);
		itemDao.save(item96);
		itemDao.save(item97);
		itemDao.save(item98);
		itemDao.save(item99);
		itemDao.save(item100);
		itemDao.save(item101);
		itemDao.save(item102);
		itemDao.save(item103);
		itemDao.save(item104);
		itemDao.save(item105);
		itemDao.save(item106);
		itemDao.save(item107);
		itemDao.save(item108);
		itemDao.save(item109);
		itemDao.save(item110);
		itemDao.save(item111);
		itemDao.save(item112);
		itemDao.save(item113);
		itemDao.save(item114);
		itemDao.save(item115);
		itemDao.save(item116);
		itemDao.save(item117);
		itemDao.save(item118);
		itemDao.save(item119);
		itemDao.save(item120);
		itemDao.save(item121);
		itemDao.save(item122);
		itemDao.save(item123);
		itemDao.save(item124);
		itemDao.save(item125);
		itemDao.save(item126);
		itemDao.save(item127);
		itemDao.save(item128);
		itemDao.save(item129);
		itemDao.save(item130);
		itemDao.save(item131);
		itemDao.save(item132);
		itemDao.save(item133);
		itemDao.save(item134);
		itemDao.save(item135);
		itemDao.save(item136);
		itemDao.save(item137);
		itemDao.save(item138);
		itemDao.save(item139);
		itemDao.save(item140);
		itemDao.save(item141);
		itemDao.save(item142);
		itemDao.save(item143);
		itemDao.save(item144);
		itemDao.save(item145);
		itemDao.save(item146);
		itemDao.save(item147);
		itemDao.save(item148);
		itemDao.save(item149);
		itemDao.save(item150);
		itemDao.save(item151);
		itemDao.save(item152);
		itemDao.save(item153);
		itemDao.save(item154);
		itemDao.save(item155);
		itemDao.save(item156);
		itemDao.save(item157);
		itemDao.save(item158);
		itemDao.save(item159);
		itemDao.save(item160);
		itemDao.save(item161);
		itemDao.save(item162);
		itemDao.save(item163);
		itemDao.save(item164);
		itemDao.save(item165);
		itemDao.save(item166);
		itemDao.save(item167);
		itemDao.save(item168);
		itemDao.save(item169);
		itemDao.save(item170);
		itemDao.save(item171);
		itemDao.save(item172);
		itemDao.save(item173);
		itemDao.save(item174);
		itemDao.save(item175);
		itemDao.save(item176);
		itemDao.save(item177);
		itemDao.save(item178);
		itemDao.save(item179);
		itemDao.save(item180);
		itemDao.save(item181);
		itemDao.save(item182);
		itemDao.save(item183);
		itemDao.save(item184);
		itemDao.save(item185);
		itemDao.save(item186);
		itemDao.save(item187);
		itemDao.save(item188);
		itemDao.save(item189);
		itemDao.save(item190);
		itemDao.save(item191);
		itemDao.save(item192);
		itemDao.save(item193);
		itemDao.save(item194);
		itemDao.save(item195);
		itemDao.save(item196);
		itemDao.save(item197);
		itemDao.save(item198);
		itemDao.save(item199);
		itemDao.save(item200);
		itemDao.save(item201);
		itemDao.save(item202);
		itemDao.save(item203);
		itemDao.save(item204);
		itemDao.save(item205);
		itemDao.save(item206);
		itemDao.save(item207);
		itemDao.save(item208);
		itemDao.save(item209);
		itemDao.save(item210);
		itemDao.save(item211);
		itemDao.save(item212);
		itemDao.save(item213);
		itemDao.save(item214);
		itemDao.save(item215);
		itemDao.save(item216);
		itemDao.save(item217);
		itemDao.save(item218);
		itemDao.save(item219);
		itemDao.save(item220);
		itemDao.save(item221);
		itemDao.save(item222);
		itemDao.save(item223);
		itemDao.save(item224);
		itemDao.save(item225);
		itemDao.save(item226);
		itemDao.save(item227);
		itemDao.save(item228);
		itemDao.save(item229);
		itemDao.save(item230);
		itemDao.save(item231);
		itemDao.save(item232);
		itemDao.save(item233);
		itemDao.save(item234);
		itemDao.save(item235);
		itemDao.save(item236);
		itemDao.save(item237);
		itemDao.save(item238);
		itemDao.save(item239);
		itemDao.save(item240);
		itemDao.save(item241);
		itemDao.save(item242);
		itemDao.save(item243);
		itemDao.save(item244);
		itemDao.save(item245);
		itemDao.save(item246);
		itemDao.save(item247);
		itemDao.save(item248);
		itemDao.save(item249);
		itemDao.save(item250);
		itemDao.save(item251);
		itemDao.save(item252);
		itemDao.save(item253);
		itemDao.save(item254);
		itemDao.save(item255);
		itemDao.save(item256);
		itemDao.save(item257);
		itemDao.save(item258);
		itemDao.save(item259);
		itemDao.save(item260);
		itemDao.save(item261);
		itemDao.save(item262);
		itemDao.save(item263);
		itemDao.save(item264);
		itemDao.save(item265);
		itemDao.save(item266);
		itemDao.save(item267);
		itemDao.save(item268);
		itemDao.save(item269);
		itemDao.save(item270);
		itemDao.save(item271);
		itemDao.save(item272);
		itemDao.save(item273);
		itemDao.save(item274);
		itemDao.save(item275);
		itemDao.save(item276);
		itemDao.save(item277);
		itemDao.save(item278);
		itemDao.save(item279);
		
		
		runeDao.save(rune1);
		runeDao.save(rune2);
		runeDao.save(rune3);
		runeDao.save(rune4);
		runeDao.save(rune5);
		runeDao.save(rune6);
		runeDao.save(rune7);
		runeDao.save(rune8);
		runeDao.save(rune9);
		runeDao.save(rune10);
		runeDao.save(rune11);
		runeDao.save(rune12);
		runeDao.save(rune13);
		runeDao.save(rune14);
		runeDao.save(rune15);
		runeDao.save(rune16);
		runeDao.save(rune17);
		runeDao.save(rune18);
		runeDao.save(rune19);
		runeDao.save(rune20);
		runeDao.save(rune21);
		runeDao.save(rune22);
		runeDao.save(rune23);
		runeDao.save(rune24);
		runeDao.save(rune25);
		runeDao.save(rune26);
		runeDao.save(rune27);
		runeDao.save(rune28);
		runeDao.save(rune29);
		runeDao.save(rune30);
		runeDao.save(rune31);
		runeDao.save(rune32);
		runeDao.save(rune33);
		runeDao.save(rune34);
		runeDao.save(rune35);
		runeDao.save(rune36);
		runeDao.save(rune37);
		runeDao.save(rune38);
		runeDao.save(rune39);
		runeDao.save(rune40);
		runeDao.save(rune41);
		runeDao.save(rune42);
		runeDao.save(rune43);
		runeDao.save(rune44);
		runeDao.save(rune45);
		runeDao.save(rune46);
		runeDao.save(rune47);
		runeDao.save(rune48);
		runeDao.save(rune49);
		runeDao.save(rune50);
		runeDao.save(rune51);
		runeDao.save(rune52);
		runeDao.save(rune53);
		runeDao.save(rune54);
		runeDao.save(rune55);
		runeDao.save(rune56);
		runeDao.save(rune57);
		runeDao.save(rune58);
		runeDao.save(rune59);
		runeDao.save(rune60);
		runeDao.save(rune61);
		runeDao.save(rune62);
		runeDao.save(rune63);
		runeDao.save(rune64);
		runeDao.save(rune65);
		runeDao.save(rune66);
		
		spellDao.save(spell1);
		spellDao.save(spell2);
		spellDao.save(spell3);
		spellDao.save(spell4);
		spellDao.save(spell5);
		spellDao.save(spell6);
		spellDao.save(spell7);
		spellDao.save(spell8);
		spellDao.save(spell9);
		spellDao.save(spell10);
		spellDao.save(spell11);
		spellDao.save(spell12);
		spellDao.save(spell13);
		spellDao.save(spell14);
		spellDao.save(spell15);
		spellDao.save(spell16);
		spellDao.save(spell17);
		spellDao.save(spell18);
		spellDao.save(spell19);

		
		skillDao.save(skill1);
		
		miscDao.save(misc1);
		
		System.out.println("Retrieve all accounts");
		for(Account a : accountDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all champions");
		for(Champion a : championDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all items");
		for(Item a : itemDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all runes");
		for(Rune a : runeDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}

		System.out.println("Retrieve all skills");
		for(Skill a : skillDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all spells");
		for(Spell a : spellDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all miscellaneous");
		for(Misc a : miscDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}


		
	}
	//prova

}
