package test;

import persistence.DAOFactory;
import persistence.UtilDao;
import persistence.dao.*;
import model.*;

public class TestDatabaseMain {

	public static void main(String[] args) {

		DAOFactory factory = DAOFactory.getDAOFactory(DAOFactory.POSTGRESQL);
		UtilDao util = factory.getUtilDAO();
		util.dropDatabase();
		util.createDatabase();
		
		AccountDao accountDao = factory.getAccountDAO();
		ChampionDao championDao = factory.getChampionDAO();
		ItemDao itemDao = factory.getItemDAO();
		RuneDao runeDao = factory.getRuneDAO();
		SpellDao spellDao = factory.getSpellDAO();
		SkillDao skillDao = factory.getSkillDAO();
		MiscDao miscDao = factory.getMiscDAO();

		Account account1 = new Account("Michele","michele123");
		Account account2 = new Account("Michelino","michele1234");
		Account account3 = new Account("Minchiele","michele12345");
		Account account4 = new Account("Robo", "ech");
		
		Champion champion1 = new Champion(1, "Annie", "champions//AnnieSquare.png");
		Champion champion2 = new Champion(2, "Olaf", "champions//OlafSquare.png");
		Champion champion3 = new Champion(3, "Galio", "champions//GalioSquare.png");
		Champion champion4 = new Champion(4, "Twisted Fate", "champions//Twisted_FateSquare.png");
		Champion champion5 = new Champion(5, "Xin Zhao", "champions//Xin_ZhaoSquare.png");
		Champion champion6 = new Champion(6, "Urgot", "champions//UrgotSquare.png");
		Champion champion7 = new Champion(7, "LeBlanc", "champions//LeBlancSquare.png");
		Champion champion8 = new Champion(8, "Vladimir", "champions//VladimirSquare.png");
		Champion champion9 = new Champion(9, "Fiddlesticks", "champions//FiddlesticksSquare.png");
		Champion champion10 = new Champion(10, "Kayle", "champions//KayleSquare.png");
		Champion champion11 = new Champion(11, "Master Yi", "champions//Master_YiSquare.png");
		Champion champion12 = new Champion(12, "Alistar", "champions//AlistarSquare.png");
		Champion champion13 = new Champion(13, "Ryze", "champions//RyzeSquare.png");
		Champion champion14 = new Champion(14, "Sion", "champions//SionSquare.png");
		Champion champion15 = new Champion(15, "Sivir", "champions//SivirSquare.png");
		Champion champion16 = new Champion(16, "Soraka", "champions//SorakaSquare.png");
		Champion champion17 = new Champion(17, "Teemo", "champions//TeemoSquare.png");
		Champion champion18 = new Champion(18, "Tristana", "champions//TristanaSquare.png");
		Champion champion19 = new Champion(19, "Warwick", "champions//WarwickSquare.png");
		Champion champion20 = new Champion(20, "Nunu", "champions//NunuSquare.png");
		Champion champion21 = new Champion(21, "Miss Fortune", "champions//Miss_FortunaSquare.png");
		Champion champion22 = new Champion(22, "Ashe", "champions//AsheSquare.png");
		Champion champion23 = new Champion(23, "Tryndamere", "champions//TryndamereSquare.png");
		Champion champion24 = new Champion(24, "Jax", "champions//JaxSquare.png");
		Champion champion25 = new Champion(25, "Morgana", "champions//MorganaSquare.png");
		Champion champion26 = new Champion(26, "Zilean", "champions//ZileanSquare.png");
		Champion champion27 = new Champion(27, "Singed", "champions//SingedSquare.png");
		Champion champion28 = new Champion(28, "Evelynn", "champions//EvelynnSquare.png");
		Champion champion29 = new Champion(29, "Twitch", "champions//TwitchSquare.png");
		Champion champion30 = new Champion(30, "Karthus", "champions//KarthusSquare.png");
		Champion champion31 = new Champion(31, "Cho'Gath", "champions//Cho'GathSquare.png");
		Champion champion32 = new Champion(32, "Amumu", "champions//AmumuSquare.png");
		Champion champion33 = new Champion(33, "Rammus", "champions//RammusSquare.png");
		Champion champion34 = new Champion(34, "Anivia", "champions//AniviaSquare.png");
		Champion champion35 = new Champion(35, "Shaco", "champions//ShacoSquare.png");
		Champion champion36 = new Champion(36, "Dr.Mundo", "champions//Dr._MundoSquare.png");
		Champion champion37 = new Champion(37, "Sona", "champions//SonaSquare.png");
		Champion champion38 = new Champion(38, "Kassadin", "champions//KassadinSquare.png");
		Champion champion39 = new Champion(39, "Irelia", "champions//IreliaSquare.png");
		Champion champion40 = new Champion(40, "Janna", "champions//JannaSquare.png");
		Champion champion41 = new Champion(41, "Gangplank", "champions//GangplankSquare.png");
		Champion champion42 = new Champion(42, "Corki", "champions//CorkiSquare.png");
		Champion champion43 = new Champion(43, "Karma", "champions//KarmaSquare.png");
		Champion champion44 = new Champion(44, "Taric", "champions//TaricSquare.png");
		Champion champion45 = new Champion(45, "Veigar", "champions//VeigarSquare.png");
		Champion champion46 = new Champion(48, "Trundle", "champions//TrundleSquare.png");
		Champion champion47 = new Champion(50, "Swain", "champions//SwainSquare.png");
		Champion champion48 = new Champion(51, "Caitlyn", "champions//CaitlynSquare.png");
		Champion champion49 = new Champion(53, "Blitzcrank", "champions//BlitcrankSquare.png");
		Champion champion50 = new Champion(54, "Malphite", "champions//MalphiteSquare.png");
		Champion champion51 = new Champion(55, "Katarina", "champions//KatarinaSquare.png");
		Champion champion52 = new Champion(56, "Nocturne", "champions//NocturneSquare.png");
		Champion champion53 = new Champion(57, "Maokai", "champions//MaokaiSquare.png");
		Champion champion54 = new Champion(58, "Renekton", "champions//RenektonSquare.png");
		Champion champion55 = new Champion(59, "Jarvan IV", "champions//Jarvan_IVSquare.png");
		Champion champion56 = new Champion(60, "Elise", "champions//EliseSquare.png");
		Champion champion57 = new Champion(61, "Orianna", "champions//OriannaSquare.png");
		Champion champion58 = new Champion(62, "Wukong", "champions//WukongSquare.png");
		Champion champion59 = new Champion(63, "Brand", "champions//BrandSquare.png");
		Champion champion60 = new Champion(64, "Lee Sin", "champions//Lee_SinSquare.png");
		Champion champion61 = new Champion(67, "Vayne", "champions//VayneSquare.png");
		Champion champion62 = new Champion(68, "Rumble", "champions//RumbleSquare.png");
		Champion champion63 = new Champion(69, "Cassiopeia", "champions//CassiopeiaSquare.png");
		Champion champion64 = new Champion(72, "Skarner", "champions//SkarnerSquare.png");
		Champion champion65 = new Champion(74, "Heimerdinger", "champions//HeimerdingerSquare.png");
		Champion champion66 = new Champion(75, "Nasus", "champions//NasusSquare.png");
		Champion champion67 = new Champion(76, "Nidalee", "champions//NidaleeSquare.png");
		Champion champion68 = new Champion(77, "Udyr", "champions//UdyrSquare.png");
		Champion champion69 = new Champion(78, "Poppy", "champions//PoppySquare.png");
		Champion champion70 = new Champion(79, "Gragas", "champions//GragasSquare.png");
		Champion champion71 = new Champion(80, "Pantheon", "champions//PantheonSquare.png");
		Champion champion72 = new Champion(81, "Ezreal", "champions//EzrealSquare.png");
		Champion champion73 = new Champion(82, "Mordekaiser", "champions//MorderkaiserSquare.png");
		Champion champion74 = new Champion(83, "Yorick", "champions//YorickSquare.png");
		Champion champion75 = new Champion(84, "Akali", "champions//AkaliSquare.png");
		Champion champion76 = new Champion(85, "Kennen", "champions//KenneSquare.png");
		Champion champion77 = new Champion(86, "Garen", "champions//GarenSquare.png");
		Champion champion78 = new Champion(89, "Leona", "champions//LeonaSquare.png");
		Champion champion79 = new Champion(90, "Malzahar", "champions//MalzaharSquare.png");
		Champion champion80 = new Champion(91, "Talon", "champions//TalonSquare.png");
		Champion champion81 = new Champion(92, "Riven", "champions//RivenSquare.png");
		Champion champion82 = new Champion(96, "Kog'Maw", "champions//Kog'MawSquare.png");
		Champion champion83 = new Champion(98, "Shen", "champions//ShenSquare.png");
		Champion champion84 = new Champion(99, "Lux", "champions//LuxSquare.png");
		Champion champion85 = new Champion(101, "Xerath", "champions//XerathSquare.png");
		Champion champion86 = new Champion(102, "Shyvana", "champions//ShyvanaSquare.png");
		Champion champion87 = new Champion(103, "Ahri", "champions//AhriSquare.png");
		Champion champion88 = new Champion(104, "Graves", "champions//GravesSquare.png");
		Champion champion89 = new Champion(105, "Fizz", "champions//FizzSquare.png");
		Champion champion90 = new Champion(106, "Volibear", "champions//VolibearSquare.png");
		Champion champion91 = new Champion(107, "Rengar", "champions//RengarSquare.png");
		Champion champion92 = new Champion(110, "Varus", "champions//VarusSquare.png");
		Champion champion93 = new Champion(111, "Nautilus", "champions//NautilusSquare.png");
		Champion champion94 = new Champion(112, "Viktor", "champions//ViktorSquare.png");
		Champion champion95 = new Champion(113, "Sejuani", "champions//SejuaniSquare.png");
		Champion champion96 = new Champion(114, "Fiora", "champions//FioraSquare.png");
		Champion champion97 = new Champion(115, "Ziggs", "champions//ZiggsSquare.png");
		Champion champion98 = new Champion(117, "Lulu", "champions//LuluSquare.png");
		Champion champion99 = new Champion(119, "Draven", "champions//DravenSquare.png");
		Champion champion100 = new Champion(120, "Hecarim", "champions//HecarimSquare.png");
		Champion champion101 = new Champion(121, "Kha'Zix", "champions//Kha'ZixSquare.png");
		Champion champion102 = new Champion(122, "Darius", "champions//DariusSquare.png");
		Champion champion103 = new Champion(126, "Jayce", "champions//JayceSquare.png");
		Champion champion104 = new Champion(127, "Lissandra", "champions//LissandraSquare.png");
		Champion champion105 = new Champion(131, "Diana", "champions//DianaSquare.png");
		Champion champion106 = new Champion(133, "Quinn", "champions//QuinnSquare.png");
		Champion champion107 = new Champion(134, "Syndra", "champions//SyndraSquare.png");
		Champion champion108 = new Champion(136, "Aurelion Sol", "champions//Aurelion_SolSquare.png");
		Champion champion109 = new Champion(141, "Kayn", "champions//KaynSquare.png");
		Champion champion110 = new Champion(142, "Zoe", "champions//ZoeSquare.png");
		Champion champion111 = new Champion(143, "Zyra", "champions//ZyraSquare.png");
		Champion champion112 = new Champion(150, "Gnar", "champions//GnarSquare.png");
		Champion champion113 = new Champion(154, "Zac", "champions//ZacSquare.png");
		Champion champion114 = new Champion(157, "Yasuo", "champions//YasuoSquare.png");
		Champion champion115 = new Champion(161, "Vel'Koz", "champions//Vel'KozSquare.png");
		Champion champion116 = new Champion(163, "Taliyah", "champions//TaliyahSquare.png");
		Champion champion117 = new Champion(164, "Camille", "champions//CamillaSquare.png");
		Champion champion118 = new Champion(201, "Braum", "champions//BraumSquare.png");
		Champion champion119 = new Champion(202, "Jhin", "champions//JhinSquare.png");
		Champion champion120 = new Champion(203, "Kindred", "champions//KindredSquare.png");
		Champion champion121 = new Champion(222, "Jinx", "champions//JinxSquare.png");
		Champion champion122 = new Champion(223, "Tahm Kench", "champions//Tahm_KenchSquare.png");
		Champion champion123 = new Champion(236, "Lucian", "champions//LucianSquare.png");
		Champion champion124 = new Champion(238, "Zed", "champions//ZedSquare.png");
		Champion champion125 = new Champion(240, "Kled", "champions//KledSquare.png");
		Champion champion126 = new Champion(245, "Ekko", "champions//EkkoSquare.png");
		Champion champion127 = new Champion(254, "Vi", "champions//ViSquare.png");
		Champion champion128 = new Champion(266, "Aatrox", "champions//AatroxSquare.png");
		Champion champion129 = new Champion(267, "Nami", "champions//NamiSquare.png");
		Champion champion130 = new Champion(268, "Azir", "champions//AzirSquare.png");
		Champion champion131 = new Champion(412, "Thresh", "champions//ThreshSquare.png");
		Champion champion132 = new Champion(420, "Illaoi", "champions//IllaoiSquare.png");
		Champion champion133 = new Champion(421, "Rek'Sai", "champions//Rek'SaiSquare.png");
		Champion champion134 = new Champion(427, "Ivern", "champions//IvernSquare.png");
		Champion champion135 = new Champion(429, "Kalista", "champions//KalistaSquare.png");
		Champion champion136 = new Champion(432, "Bard", "champions//BardSquare.png");
		Champion champion137 = new Champion(497, "Rakan", "champions//RakanSquare.png");
		Champion champion138 = new Champion(498, "Xayah", "champions//XayahSquare.png");
		Champion champion139 = new Champion(516, "Ornn", "champions//OrnnSquare.png");

		
		Item item1= new Item(1001, "Stivali della velocità", "items//Boots_of_Speed_item.png");
		Item item2= new Item(1004, "Amuleto della fata", "items//Faerie_Charm_item.png");
		Item item3= new Item(1006, "Perla del rinvigorimento", "items//Rejuvenation_Bead_item.png");
		Item item4= new Item(1011, "Cintura del gigante", "items//Giant's_Belt_item.png");
		Item item5= new Item(1018, "Cappa dell'agilità", "items//Cloak_of_Agility_item.png");
		Item item6= new Item(1026, "Bacchetta distruttiva", "items//Blasting_Wand_item.png");
		Item item7= new Item(1027, "Zaffiro di cristallo", "items//Sapphire_Crystal_item.png");
		Item item8= new Item(1028, "Rubino di cristallo", "items//Ruby_Crystal_item.png");
		Item item9= new Item(1029, "Armatura di stoffa", "items//Cloth_Armor_item.png");
		Item item10= new Item(1031, "Cotta di maglia", "items//Chain_Vest_item.png");
		Item item11= new Item(1033, "Cappa anti-magia", "items//Null-Magic_Mantle_item.png");
		Item item12= new Item(1036, "Spada lunga", "items//Long_Sword_item.png");
		Item item13= new Item(1037, "Piccone", "items//Pickaxe_item.png");
		Item item14= new Item(1038, "M.C. Spada", "items//B.F._Sword_item.png");
		Item item15= new Item(1039, "Talismano del cacciatore", "items//Hunter's_Talisman_item.png");
		Item item16= new Item(1041, "Machete del cacciatore", "items//Hunter's_Machete_item.png");
		Item item17= new Item(1042, "Daga", "items//Dagger_item.png");
		Item item18= new Item(1043, "Arco ricurvo", "items//Recurve_Bow_item.png");
		Item item19= new Item(1051, "Guanti da mischia", "items//Brawler's_Gloves_item.png");
		Item item20= new Item(1052, "Tomo del potenziamento", "items//Amplifying_Tome_item.png");
		Item item21= new Item(1053, "Scettro vampirico", "items//Vampiric_Scepter_item.png");
		Item item22= new Item(1054, "Scudo di Doran", "items//Doran's_Shield_item.png");
		Item item23= new Item(1055, "Lama di Doran", "items//Doran's_Blade_item.png");
		Item item24= new Item(1056, "Anello di Doran", "items//Doran's_Ring_item.png");
		Item item25= new Item(1057, "Mantello di Negatron", "items//Negatron_Cloak_item.png");
		Item item26= new Item(1058, "Bastone colossale", "items//Needlessly_Large_Rod_item.png");
		Item item27= new Item(1082, "Sigillo oscuro", "items//Dark_Seal_item.png");
		Item item28= new Item(1083, "Mietitore", "items//Cull_item.png");
		Item item29= new Item(1400, "Gemma del Guerriero", "items//Stalker's_Blade_(Warrior)_item.png");
		Item item30= new Item(1401, "Gemma del Colosso cinereo", "items//Stalker's_Blade_(Cinderhulk)_item.png");
		Item item31= new Item(1402, "Gemma degli Echi delle rune", "items//Stalker's_Blade_(Runic_Echoes)_item.png");
		Item item32= new Item(1408, "Gemma del Guerriero", "items//Stalker's_Blade_(Warrior)_item.png");
		Item item33= new Item(1409, "Gemma del Colosso cinereo", "items//Stalker's_Blade_(Cinderhulk)_item.png");
		Item item34= new Item(1410, "Gemma degli Echi delle rune", "items//Stalker's_Blade_(Runic_Echoes)_item.png");
		Item item35= new Item(1412, "Gemma del Guerriero", "items//Stalker's_Blade_(Warrior)_item.png");
		Item item36= new Item(1413, "Gemma del Colosso cinereo", "items//Stalker's_Blade_(Cinderhulk)_item.png");
		Item item37= new Item(1414, "Gemma degli Echi delle rune", "items//Stalker's_Blade_(Runic_Echoes)_item.png");
		Item item38= new Item(1416, "Gemma degli Artigli rossi", "items//Stalker's_Blade_(Bloodrazor)_item.png");
		Item item39= new Item(1418, "Gemma degli Artigli rossi", "items//Stalker's_Blade_(Bloodrazor)_item.png");
		Item item40= new Item(1419, "Gemma degli Artigli rossi", "items//Stalker's_Blade_(Bloodrazor)_item.png");
		Item item41= new Item(2003, "Pozione di salute", "items//Health_Potion_item.png");
		Item item42= new Item(2004, "Pozione di mana", "items//Mana_Potion_item.png");
		Item item43= new Item(2009, "Biscotto della giovinezza", "items//Total_Biscuit_of_Everlasting_Will_item.png");
		Item item44= new Item(2010, "Biscotto eterno della volontà", "items//Total_Biscuit_of_Everlasting_Will_item.png");
		Item item45= new Item(2011, "Elisir di abilità", "items//Ichor_of_Illumination_item.png");
		Item item46= new Item(2012, "Biscotto della giovinezza saccheggiato", "items//Total_Biscuit_of_Everlasting_Will_item.png");
		Item item47= new Item(2013, "Estratto dell'oracolo saccheggiato", "items//Oracle's_Extract_item.png");
		Item item48= new Item(2015, "Scheggia di Kircheis", "items//Kirche's_Shard_item.png");
		Item item49= new Item(2031, "Pozione ricaricabile", "items//Refillable_Potion_item.png");
		Item item50= new Item(2032, "Pozione del cacciatore", "items//Hunter's_Potion_item.png");
		Item item51= new Item(2033, "Pozione della corruzione", "items//Corrupting_Potion_item.png");
		Item item52= new Item(2045, "Rubino della visione", "items//Ruby_Sightstone_item.png");
		Item item53= new Item(2047, "Estratto dell'oracolo", "items//Oracle's_Extract_item.png");
		Item item54= new Item(2049, "Pietra della visione", "items//Sightstone_item.png");
		Item item55= new Item(2050, "Lume dell'esploratore", "items//Stealth_Ward_(Item)_item.png");
		Item item56= new Item(2051, "Corno del guardiano", "items//Guardian's_Horn_item.png");
		Item item57= new Item(2052, "Poro-Snax", "items//Poro-Snax_item.png");
		Item item58= new Item(2053, "Cappa rapace", "items//Raptor_Cloak_item.png");
		Item item59= new Item(2054, "Poro-Snax dietetico", "items//Poro-Snax_item.png");
		Item item60= new Item(2055, "Lume di controllo", "items//Control_Ward_item.png");
		Item item61= new Item(2056, "Lume invisibile rubato", "items//Stealth_Ward_(Item)_item.png");
		Item item62= new Item(2057, "Lume di lungavisione sbirciante", "items//Farsight_Alteration_item.png");
		Item item63= new Item(2058, "Elisir da viaggio del ferro", "items//Travel_Size_Elixir_of_Iron_item.png");
		Item item64= new Item(2059, "Elisir da viaggio della stregoneria", "items//Travel_Size_Elixir_of_Sorcery_item.png");
		Item item65= new Item(2060, "Elisir da viaggio dell'ira", "items//Travel_Size_Elixir_of_Wrath_item.png");
		Item item66= new Item(2061, "Pozione di salute rubata", "items//Health_Potion_item.png");
		Item item67= new Item(2062, "Pozione del solitario rubata", "items//Pilfered_Health_Potion_item.png");
		Item item68= new Item(2138, "Elisir del ferro", "items//Elixir_of_Iron_item.png");
		Item item69= new Item(2139, "Elisir della stregoneria", "items//Elixir_of_Sorcery_item.png");
		Item item70= new Item(2140, "Elisir dell'ira", "items//Elixir_of_Wrath_item.png");
		Item item71= new Item(2301, "Occhio degli osservatori", "items//Eye_of_the_Watchers_item.png");
		Item item72= new Item(2302, "Occhio dell'oasi", "items//Eye_of_the_Oasis_item.png");
		Item item73= new Item(2303, "Occhio dell'equinozio", "items//Eye_of_the_Equinox_item.png");
		Item item74= new Item(2319, "Scaltro sacco d'oro", "items//Sly_Sack_of_Gold_item.png");
		Item item75= new Item(2403, "Smaterializzatore", "items//Minion_Dematerializer_item.png");
		Item item76= new Item(2419, "Trasformazione in Cronografo", "items//Stopwatch_item.png");
		Item item77= new Item(2420, "Cronografo", "items//Stopwatch_item.png");
		Item item78= new Item(2421, "Cronografo rotto", "items//Broken_Stopwatch_item.png");
		Item item79= new Item(2422, "Stivali lievemente magici", "items//Slightly_Magical_Boots_item.png");
		Item item80= new Item(2423, "Cronografo", "items//Stopwatch_item.png");
		Item item81= new Item(2424, "Cronografo rotto", "items//Broken_Stopwatch_item.png");
		Item item82= new Item(3001, "Maschera dell'abisso", "items//Abyssal_Mask_item.png");
		Item item83= new Item(3003, "Scettro dell'arcangelo", "items//Archangel's_Staff_item.png");
		Item item84= new Item(3004, "Manamune", "items//Manamune_item.png");
		Item item85= new Item(3006, "Gambali del berserker", "items//Berserker's_Greaves_item.png");
		Item item86= new Item(3007, "Scettro dell'arcangelo (Carica rapida)", "items//Archangel's_Staff_item.png");
		Item item87= new Item(3008, "Manamume (Carica rapida)", "items//Manamune_item.png");
		Item item88= new Item(3009, "Stivali della rapidità", "items//Boot's_of_Swiftness_item.png");
		Item item89= new Item(3010, "Ametista degli eoni", "items//Catalyst_of_Eons_item.png");
		Item item90= new Item(3020, "Calzari del mago", "items//Sorcerer's_Shoes_item.png");
		Item item91= new Item(3022, "Martello ghiacciato", "items//Frozen_Mallet_item.png");
		Item item92= new Item(3024, "Velo glaciale", "items//Glacial_Shroud_item.png");
		Item item93= new Item(3025, "Guanto del gelo", "items//Ice_Guantlet_item.png");
		Item item94= new Item(3026, "Angelo custode", "items//Guardian_Angel_item.png");
		Item item95= new Item(3027, "Bastone secolare", "items//Rod_of_Ages_item.png");
		Item item96= new Item(3028, "Calice dell'armonia", "items//Chalice_of_Harmony_item.png");
		Item item97= new Item(3029, "Bastone secolare (Carica rapida)", "items//Rod_of_Ages_item.png");
		Item item98= new Item(3030, "Hextech GLP-800", "items//Hextech_GLP-800_item.png");
		Item item99= new Item(3031, "Frammento d'infinito", "items//Infinity_Edge_item.png");
		Item item100= new Item(3033, "Memento mori", "items//Mortal_Reminder_item.png");
		Item item101= new Item(3034, "Uccisore di giganti", "items//Giant_Slayer_item.png");
		Item item102= new Item(3035, "Sussurro fatale", "items//Last_Whisper_item.png");
		Item item103= new Item(3036, "Saluti di Lord Dominik", "items//Lord_Dominik's_Regards_item.png");
		Item item104= new Item(3040, "Abbraccio serafico", "items//Seraph's_Embrace_item.png");
		Item item105= new Item(3041, "Tomo Mejai ruba-anime", "items//Mejai's_Soulstealer_item.png");
		Item item106= new Item(3042, "Muramana", "items//Muramana_item.png");
		Item item107= new Item(3043, "Muramana", "items//Muramana_item.png");
		Item item108= new Item(3044, "Flagello", "items//Phage_item.png");
		Item item109= new Item(3046, "Danzatore fantasma", "items//Phantom_Dancer_item.png");
		Item item110= new Item(3047, "Calzari del ninja", "items//Ninja_Tabi_item.png");
		Item item111= new Item(3048, "Abbraccio serafico", "items//Seraph's_Embrace_item.png");
		Item item112= new Item(3050, "Convergenza di Zeke", "items//Zeke's_Convergence_item.png");
		Item item113= new Item(3052, "Pugno di Jaurim", "items//Jaurim's_Fist_item.png");
		Item item114= new Item(3053, "Pegno di Sterak", "items//Sterak's_Gage_item.png");
		Item item115= new Item(3056, "Spaccaresistenze", "items//Ohmwrecker_item.png");
		Item item116= new Item(3057, "Fulgore", "items//Sheen_item.png");
		Item item117= new Item(3060, "Stendardo del comando", "items//Banner_of_Command_item.png");
		Item item118= new Item(3065, "Corazza spirituale", "items//Spirit_Visage_item.png");
		Item item119= new Item(3067, "Gemma infuocata", "items//Kindlegem_item.png");
		Item item120= new Item(3068, "Mantello del Sole", "items//Sunfire_Cape_item.png");
		Item item121= new Item(3069, "Talismano dell'ascensione", "items//Talisman_of_Ascension_item.png");
		Item item122= new Item(3070, "Lacrime della dea", "items//Tear_of_the_Goddess_item.png");
		Item item123= new Item(3071, "Mannaia oscura", "items//Black_Cleaver_item.png");
		Item item124= new Item(3072, "La Bramasangue", "items//Death's_Dance_item.png");
		Item item125= new Item(3073, "Lacrima della dea (Carica rapida)", "items//Tear_of_the_Goddess_item.png");
		Item item126= new Item(3074, "Idra famelica", "items//Ravenous_Hydra_item.png");
		Item item127= new Item(3075, "Corazza spinata", "items//Thornmail_item.png");
		Item item128= new Item(3076, "Corpetto di rovi", "items//Bramble_Vest_item.png");
		Item item129= new Item(3077, "Tiamat", "items//Tiamat_item.png");
		Item item130= new Item(3078, "Virtù della Triade", "items//Trinity_Force_item.png");
		Item item131= new Item(3082, "Armatura del custode", "items//Warden's_Mail_item.png");
		Item item132= new Item(3083, "Armatura di Warmog", "items//Warmog's_Armor_item.png");
		Item item133= new Item(3084, "Cotta di maglia del signore supremo", "items//Warmog's_Armor_item.png");
		Item item134= new Item(3085, "Uragano di Runaan", "items//Runaan's_Hurricane_item.png");
		Item item135= new Item(3086, "Fervore", "items//Fervor_item.png");
		Item item136= new Item(3087, "Pugnale di Statikk", "items//Statikk_Shiv_item.png");
		Item item137= new Item(3089, "Copricapo di Rabadon", "items//Rabadon's_Deathcap_item.png");
		Item item138= new Item(3090, "Copricapo di Wooglet", "items//Wooglet's_Witchcap_item.png");
		Item item139= new Item(3091, "Speranza perduta", "items//Wit's_End_item.png");
		Item item140= new Item(3092, "Volere della regina dei ghiacci", "items//Frost_Queen's_Claim_item.png");
		Item item141= new Item(3094, "Archibugio a ripetizione", "items//Rapid_Firecannon_item.png");
		Item item142= new Item(3096, "Medaglione del nomade", "items//Nomad's_Medallion_item.png");
		Item item143= new Item(3097, "Difesa di Targon", "items//Targon's_Brace_item.png");
		Item item144= new Item(3098, "Zanna di ghiaccio", "items//Frostfang_item.png");
		Item item145= new Item(3100, "Terrore dei lich", "items//Lich_Bane_item.png");
		Item item146= new Item(3101, "Pungolo", "items//Stinger_item.png");
		Item item147= new Item(3102, "Velo della Banshee", "items//Banshee's_Veil_item.png");
		Item item148= new Item(3104, "Distruttore di Lord Van Damm", "items//Lord_Van_Dam's_Pillager_item.png");
		Item item149= new Item(3105, "Egida della legione", "items//Aegis_of_the_LegionS_item.png");
		Item item150= new Item(3107, "Redenzione", "items//Redemption_item.png");
		Item item151= new Item(3108, "Codice del diavolo", "items//Fiendish_Codex_item.png");
		Item item152= new Item(3109, "Voto del cavaliere", "items//Knight's_Vow_item.png");
		Item item153= new Item(3110, "Fulcro dei geli", "items//Frozen_Heart_item.png");
		Item item154= new Item(3111, "Calzari di mercurio", "items//Mercury's_Treads_item.png");
		Item item155= new Item(3112, "Globo del guardiano", "items//.png");
		Item item156= new Item(3113, "Fiamma eterea", "items//Aether_Wisp_item.png");
		Item item157= new Item(3114, "Idolo proibito", "items//Forbidden_item.png");
		Item item158= new Item(3115, "Dente di Nashor", "items//Nashor's_Tooth_item.png");
		Item item159= new Item(3116, "Scettro di cristallo di Rylai", "items//Rylai's_Crystal_Scepter_item.png");
		Item item160= new Item(3117, "Stivali della mobilità", "items//Boots_of_Mobility_item.png");
		Item item161= new Item(3122, "Accetta malefica", "items//Dagger_item.png");
		Item item162= new Item(3123, "Chiamata del carnefice", "items//Executioner's_Calling_item.png");
		Item item163= new Item(3124, "Furia di Guinsoo", "items//Guinsoo's_Rageblade_item.png");
		Item item164= new Item(3133, "Martello da guerra di Caulfield", "items//Caulfield's_Warhammer_item.png");
		Item item165= new Item(3134, "Lungo pugnale seghettato", "items//Serrated_Dirk_item.png");
		Item item166= new Item(3135, "Bastone del Vuoto", "items//Void_Staff_item.png");
		Item item167= new Item(3136, "Maschera stregata", "items//Haunting_Guise_item.png");
		Item item168= new Item(3137, "lama del derviscio", "items//Dagger_item.png");
		Item item169= new Item(3139, "Scimitarra di Mercurio", "items//Mercurial_Scimitar_item.png");
		Item item170= new Item(3140, "Fascia d'argento vivo", "items//Quicksilver_Sash_item.png");
		Item item171= new Item(3142, "Lama di Youmuu", "items//Youmuu's_Ghostblade_item.png");
		Item item172= new Item(3143, "Orgoglio di Randuin", "items//Randuin's_Omen_item.png");
		Item item173= new Item(3144, "Sciabola di Bilgewater", "items//Bilgewater_Cutlass_item.png");
		Item item174= new Item(3145, "Revolver Hextech", "items//Hextech_Revolver_item.png");
		Item item175= new Item(3146, "Pistola a lame hextech", "items//Hextech_Gunblade_item.png");
		Item item176= new Item(3147, "Lama crepuscolare di Draktharr", "items//Duskblade_of_Draktharr_item.png");
		Item item177= new Item(3151, "Tormento di Liandry", "items//Liandry's_Torment_item.png");
		Item item178= new Item(3152, "Protocintura hextech 01", "items//Hextech_Protobelt-01_item.png");
		Item item179= new Item(3153, "Lama del re in rovina", "items//Blade_of_the_Ruined_King_item.png");
		Item item180= new Item(3155, "Mangiamagia", "items//Hexdrinker_item.png");
		Item item181= new Item(3156, "Fauci di Malmortius", "items//Maw_of_Malmortius_item.png");
		Item item182= new Item(3157, "Clessidra di Zhonya", "items//Zhonya's_Hourglass_item.png");
		Item item183= new Item(3158, "Stivali dell'acume di Ionia", "items//Ionian_Boots_of_Lucidity_item.png");
		Item item184= new Item(3165, "Morellonomicon", "items//Morellonomicon_item.png");
		Item item185= new Item(3170, "Lama della Luna", "items//Moonflair_Spellblade_item.png");
		Item item186= new Item(3174, "Empio Graal di Athene", "items//Athene's_Unholy_Grail_item.png");
		Item item187= new Item(3175, "Testa di Kha'Zix", "items//Dagger_item.png");
		Item item188= new Item(3181, "Lama sanguigna", "items//The_Bloodthirster_item.png");
		Item item189= new Item(3184, "Martello del guardiano", "items//Guardian's_Hammer_item.png");
		Item item190= new Item(3185, "Il portatore di luce", "items//The_Lightbringer_item.png");
		Item item191= new Item(3187, "Occhio arcano", "items//Hextech_Sweeper_item.png");
		Item item192= new Item(3190, "Medaglione dei Solari di ferro", "items//Locket_of_the_Iron_Solari_item.png");
		Item item193= new Item(3191, "Parabraccia del cercatore", "items//Seeker's_Armguard_item.png");
		Item item194= new Item(3193, "Lastrapietra del gargoyle", "items//Gargoyle_Stoneplate_item.png");
		Item item195= new Item(3194, "Elmo adattivo", "items//Adaptive_Helm_item.png");
		Item item196= new Item(3196, "Nucleo incantato mk-1", "items//The_Hex_Core_mk-1_item.png");
		Item item197= new Item(3197, "Nucleo incantato mk-2", "items//The_Hex_Core_mk-2_item.png");
		Item item198= new Item(3198, "Nucleo incantato perfetto", "items//Perfect_Hex_Core_item.png");
		Item item199= new Item(3200, "Nucleo incantato prototipo", "items//Prototype_Hex_Core_item.png");
		Item item200= new Item(3211, "Capuccio spettrale", "items//Spectre's_Cowl_item.png");
		Item item201= new Item(3222, "Crogiolo di Mikael", "items//Mikael's_Crucible_item.png");
		Item item202= new Item(3252, "Lungo pugnale del bracconiere", "items//Poacher's_Dirk_item.png");
		Item item203= new Item(3285, "Eco di Luden", "items//Luden's_Echo_item.png");
		Item item204= new Item(3301, "Moneta antica", "items//Ancient_Coin_item.png");
		Item item205= new Item(3302, "Scudo reliquia", "items//Relic_Shield_item.png");
		Item item206= new Item(3303, "Vantaggio del mago ladro", "items//Spellthief's_Edge_item.png");
		Item item207= new Item(3340, "Totem guardiano (Trinket)", "items//Trinket_Ward_item.png");
		Item item208= new Item(3341, "Lente mobile (Trinket)", "items//Sweeping_Lens_item.png");
		Item item209= new Item(3345, "Ancora spirituale (Trinket)", "items//Dagger_item.png");
		Item item210= new Item(3348, "Occhio arcano", "items//Hextech_Sweeper_item.png");
		Item item211= new Item(3361, "Totem invisibile maggiore (Trinket)", "items//Warding_Totem_item.png");
		Item item212= new Item(3362, "Totem della visione maggiore (Trinket)", "items//Farsight_Alteration_item.png");
		Item item213= new Item(3363, "Modifica lungavisione", "items//Farsight_Alteration_item.png");
		Item item214= new Item(3364, "Modifica oracolo", "items//Oracle_Alteration_item.png");
		Item item215= new Item(3371, "Frammento incandescente", "items//Molten_Edge_item.png");
		Item item216= new Item(3373, "Mantello della forgia", "items//Forgefire_Cape_item.png");
		Item item217= new Item(3374, "Corona funebre di Rabadon", "items//Rabadon's_Deathcrown_item.png");
		Item item218= new Item(3379, "Maschera infernale", "items//Infernal_Mask_item.png");
		Item item219= new Item(3380, "Mannaia di ossidiana", "items//The_Obsidian_Cleaver_item.png");
		Item item220= new Item(3382, "Salvezza", "items//Salvation_item.png");
		Item item221= new Item(3383, "Diadema dei Solari di ferro", "items//Circlet_of_the_Iron_Solari_item.png");
		Item item222= new Item(3384, "Fusione della trinità", "items//Trinity_Fusion_item.png");
		Item item223= new Item(3385, "Corona di Wooglet", "items//Wooglet's_Witchcrown_item.png");
		Item item224= new Item(3386, "Paradosso di Zhonya", "items//Zhonya's_Paradox_item.png");
		Item item225= new Item(3401, "Volto della montagna", "items//Face_of_the_Mountain_item.png");
		Item item226= new Item(3410, "Testa di Kha'Zix", "items//Dagger_item.png");
		Item item227= new Item(3416, "Testa di Kha'Zix", "items//Dagger_item.png");
		Item item228= new Item(3422, "Testa di Kha'Zix", "items//Dagger_item.png");
		Item item229= new Item(3455, "Testa di Kha'Zix", "items//Dagger_item.png");
		Item item230= new Item(3460, "Trascendenza dorata", "items//Golden_Trascendence_item.png");
		Item item231= new Item(3461, "Trascendenza dorata (disattivata)", "items//Golden_Trascendence_item.png");
		Item item232= new Item(3462, "Pietra divinatoria (trinket)", "items//Farsight_Alteration_item.png");
		Item item233= new Item(3504, "Incensiere ardente", "items//Ardent_Censer_item.png");
		Item item234= new Item(3508, "Predatore d'essenza", "items//Essence_Reaver_item.png");
		Item item235= new Item(3512, "Portale Zz'Rot", "items//Zz'Rot_Portal_item.png");
		Item item236= new Item(3513, "Occhio del Messaggero", "items//Eye_of_the_Herald_buff.png");
		Item item237= new Item(3599, "Lancia oscura", "items//The_Black_Spear_item.png");
		Item item238= new Item(3630, "Teletrasporto d'assedio", "items//Port_Pad_item.png");
		Item item239= new Item(3631, "Ballista d'assedio", "items//Siege_Ballista_item.png");
		Item item240= new Item(3633, "Teletrasporto d'assedio", "items//Port_Pad_item.png");
		Item item241= new Item(3634, "Torre: Raggio della rovina", "items//Tower-_Beam_of_Ruination_item.png");
		Item item242= new Item(3635, "Piattaforma di teletrasporto", "items//Port_Pad_Item_item.png");
		Item item243= new Item(3636, "Torre: Bastione della tempesta", "items//Tower-_Storm_Bulwark_item.png");
		Item item244= new Item(3637, "Assedio al nexus, Slot arma d'assedio", "items//Dagger_item.png");
		Item item245= new Item(3640, "Zona Flash", "items//Flash_Zone_item.png");
		Item item246= new Item(3641, "Stendardo dell'avanguardia", "items//Vanguard_Banner_item.png");
		Item item247= new Item(3642, "Rimborso assedio", "items//Dagger_item.png");
		Item item248= new Item(3643, "Campo entropico", "items//Entropy_Field_item.png");
		Item item249= new Item(3645, "Pietra divinatoria (trinket)", "items//Farsight_Alteration_item.png");
		Item item250= new Item(3647, "Totem scudo", "items//Shield_Totem_item.png");
		Item item251= new Item(3649, "Illuminatore d'assedio", "items//Dagger_item.png");
		Item item252= new Item(3671, "Gemma del Guerriero", "items//Warrior_item.png");
		Item item253= new Item(3672, "Gemma del Colosso cinereo", "items//Juggernaut_item.png");
		Item item254= new Item(3673, "Gemma degli Echi delle rune", "items//Magus_item.png");
		Item item255= new Item(3675, "Gemma degli Artigli rossi", "items//Bloodrazor_item.png");
		Item item256= new Item(3680, "Snax glassato", "items//Frosted_Snax_item.png");
		Item item257= new Item(3681, "Snax superpiccante", "items//Super_Spicy_Snax_item.png");
		Item item258= new Item(3682, "Snax espresso", "items//Espresso_Snax_item.png");
		Item item259= new Item(3683, "Pacchetto Snax arcobaleno!", "items//Ranbow_Snax_Party_Pack!_item.png");
		Item item260= new Item(3690, "Catena cosmica", "items//Cosmic_Shackle_item.png");
		Item item261= new Item(3691, "Lanterna della Singolarità", "items//Singularity_Lantern_item.png");
		Item item262= new Item(3692, "Falce della Materia oscura", "items//Dark_Matter_Scythe_item.png");
		Item item263= new Item(3693, "Stivali gravitazionali", "items//Gravity_Boots_item.png");
		Item item264= new Item(3694, "Mantello stellare", "items//Cloak_of_Stars_item.png");
		Item item265= new Item(3695, "Sigillo della Stella Oscura", "items//Dark_Star_Sigil_item.png");
		Item item266= new Item(3706, "Lama del cacciatore", "items//Stalker's_Blade_item.png");
		Item item267= new Item(3711, "Coltello del segugio", "items//Tracker's_Knife_item.png");
		Item item268= new Item(3715, "Sciabola del soldato", "items//Skirmisher's_Sabre_item.png");
		Item item269= new Item(3742, "Corazza dell'uomo morto", "items//Dead_Man's_Plate_item.png");
		Item item270= new Item(3748, "Idra titanica", "items//Titanic_Hydra_item.png");
		Item item271= new Item(3751, "Tizzone di Bami", "items//Bami's_Cinder_item.png");
		Item item272= new Item(3800, "Gloria del giusto", "items//Righteous_Glory_item.png");
		Item item273= new Item(3801, "Bracciale cristallino", "items//Crystalline_Bracer_item.png");
		Item item274= new Item(3802, "Capitolo perduto", "items//Lost_Chapter_item.png");
		Item item275= new Item(3812, "Danza della Morte", "items//Death's_Dance_item.png");
		Item item276= new Item(3814, "Fine della notte", "items//Edge_of_Night_item.png");
		Item item277= new Item(3901, "Fuoco a volontà", "items//Fire_at_Will_item.png");
		Item item278= new Item(3902, "Figlia della Morte", "items//Death's_Daughter_item.png");
		Item item279= new Item(3903, "Morale alto", "items//Raise_Morale_item.png");
		
		
		
		Rune rune1= new Rune(8000, "Precisione", "runes//Precision_icon.png");
		Rune rune2= new Rune(8100, "Dominazione", "runes//Domination_icon.png");
		Rune rune3= new Rune(8200, "Stregoneria", "runes//Sorcery_icon.png");
		Rune rune4= new Rune(8300, "Ispirazione", "runes//Inspiration_icon.png");
		Rune rune5= new Rune(8400, "Determinazione", "runes//Resolve_icon.png");
		Rune rune6= new Rune(7000, "Template", "runes//Predator_rune.png");
		Rune rune7= new Rune(8005, "Attacco sostenuto", "runes//Press_the_Attack_rune.png");
		Rune rune8= new Rune(8008, "Tempo letale", "runes//Lethal_Tempo_rune.png");
		Rune rune9= new Rune(8009, "Presenza di spirito", "runes//Presence_of_Mind_rune.png");
		Rune rune10= new Rune(8014, "Colpo di grazia", "runes//Coup_de_Grace_rune.png");
		Rune rune11= new Rune(8017, "Colpo profondo", "runes//Cut_Down_rune.png");
		Rune rune12= new Rune(8021, "Piede lesto", "runes//Fleet_Footwork_rune.png");
		Rune rune13= new Rune(8105, "Cacciatore implacabile", "runes//Relentless_Hunter_rune.png");
		Rune rune14= new Rune(8112, "Elettroshock", "runes//Electrocute_rune.png");
		Rune rune15= new Rune(8120, "Poro Fantasma", "runes//Ghost_Poro_rune.png");
		Rune rune16= new Rune(8124, "Predatore", "runes//Predator_rune.png");
		Rune rune17= new Rune(8126, "Colpo basso", "runes//Cheap_Shot_rune.png");
		Rune rune18= new Rune(8128, "Raccolto oscuro", "runes//Dark_Harvest_rune.png");
		Rune rune19= new Rune(8134, "Ingegnoso cacciatore", "runes//Ingenious_Hunter_rune.png");
		Rune rune20= new Rune(8135, "Cacciatore famelico", "runes//Ravenous_Hunter_rune.png");
		Rune rune21= new Rune(8136, "Lume zombi", "runes//Zombie_Ward_rune.png");
		Rune rune22= new Rune(8138, "Collezione di bulbi", "runes//Eyeball_Collection_rune.png");
		Rune rune23= new Rune(8139, "Assaggio di sangue", "runes//Taste_of_Blood_rune.png");
		Rune rune24= new Rune(8143, "Impatto improvviso", "runes//Sudden_Impact_rune.png");
		Rune rune25= new Rune(8210, "Trascendenza", "runes//Trascendence_rune.png");
		Rune rune26= new Rune(8214, "Evoca Aery", "runes//Summon_Aery_rune.png");
		Rune rune27= new Rune(8224, "Sfera dell'annullamento", "runes//Nullifying_Orb_rune.png");
		Rune rune28= new Rune(8226, "Fascia del flusso", "runes//Manaflow_Band_rune.png");
		Rune rune29= new Rune(8229, "Cometa arcana", "runes//Arcane_Comet_rune.png");
		Rune rune30= new Rune(8230, "Scatto fasico", "runes//Phase_Rush_rune.png");
		Rune rune31= new Rune(8232, "Camminare sull'acqua", "runes//Waterwalking_rune.png");
		Rune rune32= new Rune(8233, "Concentrazione assoluta", "runes//Absolute_Focus_rune.png");
		Rune rune33= new Rune(8234, "Celerità", "runes//Celerity_rune.png");
		Rune rune34= new Rune(8236, "Tempesta incombente", "runes//Gathering_Storm_rune.png");
		Rune rune35= new Rune(8237, "Bruciare", "runes//Scorch_rune.png");
		Rune rune36= new Rune(8242, "Risoluto", "runes//Unflinching_rune.png");
		Rune rune37= new Rune(8243, "Il cappello supremo", "runes//The_Ultimate_Hat_rune.png");
		Rune rune38= new Rune(8299, "L'ultima sfida", "runes//Last_Stand_rune.png");
		Rune rune39= new Rune(8304, "Calzature magiche", "runes//Magical_Footwear_rune.png");
		Rune rune40= new Rune(8306, "Marchingegno Hexflash", "runes//Hextech_Flashtraption_rune.png");
		Rune rune41= new Rune(8313, "Tempismo perfetto", "runes//Perfect_Timing_rune.png");
		Rune rune42= new Rune(8316, "Smaterializzatore", "runes//Minion_Dematerializer_rune.png");
		Rune rune43= new Rune(8321, "Mercato del futuro", "runes//Future_Market_rune.png");
		Rune rune44= new Rune(8326, "Libro incantesimi non sigillato", "runes//Unsealead_Spellbook_rune.png");
		Rune rune45= new Rune(8339, "Corpo celeste", "runes//Celestial_Body_rune.png");
		Rune rune46= new Rune(8345, "Consegna biscotti", "runes//Biscuit_Delivery_rune.png");
		Rune rune47= new Rune(8347, "Intuito cosmico", "runes//Cosmic_Insight_rune.png");
		Rune rune48= new Rune(8351, "Potenziamento glaciale", "runes//Glacial_Augment_rune.png");
		Rune rune49= new Rune(8359, "Cleptomanzia", "runes//Kleptomancy_rune.png");
		Rune rune50= new Rune(8410, "Velocità di avvicinamento", "runes//Approach_Velocity_rune.png");
		Rune rune51= new Rune(8429, "Preparazione fisica", "runes//Conditioning_rune.png");
		Rune rune52= new Rune(8430, "Pelle di ferro", "runes//Iron_Skin_rune.png");
		Rune rune53= new Rune(8435, "Guscio a specchio", "runes//Mirror_Shell_rune.png");
		Rune rune54= new Rune(8437, "Presa dell'immortale", "runes//Undying_Grasp_rune.png");
		Rune rune55= new Rune(8439, "Scossa di assestamento", "runes//Aftershock_rune.png");
		Rune rune56= new Rune(8444, "Secondo fiato", "runes//Second_Wind_rune.png");
		Rune rune57= new Rune(8446, "Demolire", "runes//Demolish_rune.png");
		Rune rune58= new Rune(8451, "Crescita eccessiva", "runes//Overgrowth_rune.png");
		Rune rune59= new Rune(8453, "Rivitalizzare", "runes//Revitalize_rune.png");
		Rune rune60= new Rune(8465, "Sorvegliante", "runes//Guardian_rune.png");
		Rune rune61= new Rune(9101, "Sovraguarigione", "runes//Overheal_rune.png");
		Rune rune62= new Rune(9103, "Leggenda: Stirpe", "runes//Legend-_Bloodline_rune.png");
		Rune rune63= new Rune(9104, "Leggenda: Alacrità", "runes//Legend-_Alacrity_rune.png");
		Rune rune64= new Rune(9105, "Leggenda: Tenacità", "runes//Tenacity_rune.png");
		Rune rune65= new Rune(9111, "Trionfo", "runes//Triumph_rune.png");
		Rune rune66= new Rune(8463, "Fonte vitale", "runes//Font_of_Life_rune.png");
		
		Spell spell1=new Spell(34, "Assedio al nexus: Slot arma d'assedio", "spells//Flash.png");
		Spell spell2=new Spell(12, "Teletrasporto", "spells//Teleport.png");
		Spell spell3=new Spell(33, "Assedio al nexus: Slot arma d'assedio", "spells//Flash.png");
		Spell spell4=new Spell(3, "Sfinimento", "spells//Exhaust.png");
		Spell spell5=new Spell(21, "Barriera", "spells//Barrier.png");
		Spell spell6=new Spell(13, "Chiarezza", "spells//Clarity.png");
		Spell spell7=new Spell(39, "Ultra marchio (lanciato velocemente)", "spells//Mark.png");
		Spell spell8=new Spell(4, "Flash", "spells//Flash.png");
		Spell spell9=new Spell(32, "Marchio", "spells//Mark.png");
		Spell spell10=new Spell(14, "Ustione", "spells//Ignite.png");
		Spell spell11=new Spell(36, "Incantesimi dell'evocatore disabilitati", "spells//Flash.png");
		Spell spell12=new Spell(35, "Incantesimi dell'evocatore disabilitati", "spells//Flash.png");
		Spell spell13=new Spell(30, "Teleporo!", "spells//Mark.png");
		Spell spell14=new Spell(6, "Spettralità", "spells//Ghost.png");
		Spell spell15=new Spell(-1, "Ultra scatto (velocissimo!)", "spells//Dash.png");
		Spell spell16=new Spell(7, "Guarigione", "spells//Heal.png");
		Spell spell17=new Spell(31, "Lancio del Poro", "spells//Mark.png");
		Spell spell18=new Spell(1, "Purificazione", "spells//Cleanse.png");
		Spell spell19=new Spell(11, "Punizione", "spells//Smite.png");

		
		Skill skill1= new Skill (1, "Test", "1 ");
	
		Misc misc1= new Misc (1, "test", "1");
		
		
		accountDao.save(account1);
		accountDao.save(account2);
		accountDao.save(account3);
		accountDao.save(account4);
		
		championDao.save(champion1);
		championDao.save(champion2);
		championDao.save(champion3);
		championDao.save(champion4);
		championDao.save(champion5);
		championDao.save(champion6);
		championDao.save(champion7);
		championDao.save(champion8);
		championDao.save(champion9);
		championDao.save(champion10);
		championDao.save(champion11);
		championDao.save(champion12);
		championDao.save(champion13);
		championDao.save(champion14);
		championDao.save(champion15);
		championDao.save(champion16);
		championDao.save(champion17);
		championDao.save(champion18);
		championDao.save(champion19);
		championDao.save(champion20);
		championDao.save(champion21);
		championDao.save(champion22);
		championDao.save(champion23);
		championDao.save(champion24);
		championDao.save(champion25);
		championDao.save(champion26);
		championDao.save(champion27);
		championDao.save(champion28);
		championDao.save(champion29);
		championDao.save(champion30);
		championDao.save(champion31);
		championDao.save(champion32);
		championDao.save(champion33);
		championDao.save(champion34);
		championDao.save(champion35);
		championDao.save(champion36);
		championDao.save(champion37);
		championDao.save(champion38);
		championDao.save(champion39);
		championDao.save(champion40);
		championDao.save(champion41);
		championDao.save(champion42);
		championDao.save(champion43);
		championDao.save(champion44);
		championDao.save(champion45);
		championDao.save(champion46);
		championDao.save(champion47);
		championDao.save(champion48);
		championDao.save(champion49);
		championDao.save(champion50);
		championDao.save(champion51);
		championDao.save(champion52);
		championDao.save(champion53);
		championDao.save(champion54);
		championDao.save(champion55);
		championDao.save(champion56);
		championDao.save(champion57);
		championDao.save(champion58);
		championDao.save(champion59);
		championDao.save(champion60);
		championDao.save(champion61);
		championDao.save(champion62);
		championDao.save(champion63);
		championDao.save(champion64);
		championDao.save(champion65);
		championDao.save(champion66);
		championDao.save(champion67);
		championDao.save(champion68);
		championDao.save(champion69);
		championDao.save(champion70);
		championDao.save(champion71);
		championDao.save(champion72);
		championDao.save(champion73);
		championDao.save(champion74);
		championDao.save(champion75);
		championDao.save(champion76);
		championDao.save(champion77);
		championDao.save(champion78);
		championDao.save(champion79);
		championDao.save(champion80);
		championDao.save(champion81);
		championDao.save(champion82);
		championDao.save(champion83);
		championDao.save(champion84);
		championDao.save(champion85);
		championDao.save(champion86);
		championDao.save(champion87);
		championDao.save(champion88);
		championDao.save(champion89);
		championDao.save(champion90);
		championDao.save(champion91);
		championDao.save(champion92);
		championDao.save(champion93);
		championDao.save(champion94);
		championDao.save(champion95);
		championDao.save(champion96);
		championDao.save(champion97);
		championDao.save(champion98);
		championDao.save(champion99);
		championDao.save(champion100);
		championDao.save(champion101);
		championDao.save(champion102);
		championDao.save(champion103);
		championDao.save(champion104);
		championDao.save(champion105);
		championDao.save(champion106);
		championDao.save(champion107);
		championDao.save(champion108);
		championDao.save(champion109);
		championDao.save(champion110);
		championDao.save(champion111);
		championDao.save(champion112);
		championDao.save(champion113);
		championDao.save(champion114);
		championDao.save(champion115);
		championDao.save(champion116);
		championDao.save(champion117);
		championDao.save(champion118);
		championDao.save(champion119);
		championDao.save(champion120);
		championDao.save(champion121);
		championDao.save(champion122);
		championDao.save(champion123);
		championDao.save(champion124);
		championDao.save(champion125);
		championDao.save(champion126);
		championDao.save(champion127);
		championDao.save(champion128);
		championDao.save(champion129);
		championDao.save(champion130);
		championDao.save(champion131);
		championDao.save(champion132);
		championDao.save(champion133);
		championDao.save(champion134);
		championDao.save(champion135);
		championDao.save(champion136);
		championDao.save(champion137);
		championDao.save(champion138);
		championDao.save(champion139);
		
		itemDao.save(item1);
		itemDao.save(item2);
		itemDao.save(item3);
		itemDao.save(item4);
		itemDao.save(item5);
		itemDao.save(item6);
		itemDao.save(item7);
		itemDao.save(item8);
		itemDao.save(item9);
		itemDao.save(item10);
		itemDao.save(item11);
		itemDao.save(item12);
		itemDao.save(item13);
		itemDao.save(item14);
		itemDao.save(item15);
		itemDao.save(item16);
		itemDao.save(item17);
		itemDao.save(item18);
		itemDao.save(item19);
		itemDao.save(item20);
		itemDao.save(item21);
		itemDao.save(item22);
		itemDao.save(item23);
		itemDao.save(item24);
		itemDao.save(item25);
		itemDao.save(item26);
		itemDao.save(item27);
		itemDao.save(item28);
		itemDao.save(item29);
		itemDao.save(item30);
		itemDao.save(item31);
		itemDao.save(item32);
		itemDao.save(item33);
		itemDao.save(item34);
		itemDao.save(item35);
		itemDao.save(item36);
		itemDao.save(item37);
		itemDao.save(item38);
		itemDao.save(item39);
		itemDao.save(item40);
		itemDao.save(item41);
		itemDao.save(item42);
		itemDao.save(item43);
		itemDao.save(item44);
		itemDao.save(item45);
		itemDao.save(item46);
		itemDao.save(item47);
		itemDao.save(item48);
		itemDao.save(item49);
		itemDao.save(item50);
		itemDao.save(item51);
		itemDao.save(item52);
		itemDao.save(item53);
		itemDao.save(item54);
		itemDao.save(item55);
		itemDao.save(item56);
		itemDao.save(item57);
		itemDao.save(item58);
		itemDao.save(item59);
		itemDao.save(item60);
		itemDao.save(item61);
		itemDao.save(item62);
		itemDao.save(item63);
		itemDao.save(item64);
		itemDao.save(item65);
		itemDao.save(item66);
		itemDao.save(item67);
		itemDao.save(item68);
		itemDao.save(item69);
		itemDao.save(item70);
		itemDao.save(item71);
		itemDao.save(item72);
		itemDao.save(item73);
		itemDao.save(item74);
		itemDao.save(item75);
		itemDao.save(item76);
		itemDao.save(item77);
		itemDao.save(item78);
		itemDao.save(item79);
		itemDao.save(item80);
		itemDao.save(item81);
		itemDao.save(item82);
		itemDao.save(item83);
		itemDao.save(item84);
		itemDao.save(item85);
		itemDao.save(item86);
		itemDao.save(item87);
		itemDao.save(item88);
		itemDao.save(item89);
		itemDao.save(item90);
		itemDao.save(item91);
		itemDao.save(item92);
		itemDao.save(item93);
		itemDao.save(item94);
		itemDao.save(item95);
		itemDao.save(item96);
		itemDao.save(item97);
		itemDao.save(item98);
		itemDao.save(item99);
		itemDao.save(item100);
		itemDao.save(item101);
		itemDao.save(item102);
		itemDao.save(item103);
		itemDao.save(item104);
		itemDao.save(item105);
		itemDao.save(item106);
		itemDao.save(item107);
		itemDao.save(item108);
		itemDao.save(item109);
		itemDao.save(item110);
		itemDao.save(item111);
		itemDao.save(item112);
		itemDao.save(item113);
		itemDao.save(item114);
		itemDao.save(item115);
		itemDao.save(item116);
		itemDao.save(item117);
		itemDao.save(item118);
		itemDao.save(item119);
		itemDao.save(item120);
		itemDao.save(item121);
		itemDao.save(item122);
		itemDao.save(item123);
		itemDao.save(item124);
		itemDao.save(item125);
		itemDao.save(item126);
		itemDao.save(item127);
		itemDao.save(item128);
		itemDao.save(item129);
		itemDao.save(item130);
		itemDao.save(item131);
		itemDao.save(item132);
		itemDao.save(item133);
		itemDao.save(item134);
		itemDao.save(item135);
		itemDao.save(item136);
		itemDao.save(item137);
		itemDao.save(item138);
		itemDao.save(item139);
		itemDao.save(item140);
		itemDao.save(item141);
		itemDao.save(item142);
		itemDao.save(item143);
		itemDao.save(item144);
		itemDao.save(item145);
		itemDao.save(item146);
		itemDao.save(item147);
		itemDao.save(item148);
		itemDao.save(item149);
		itemDao.save(item150);
		itemDao.save(item151);
		itemDao.save(item152);
		itemDao.save(item153);
		itemDao.save(item154);
		itemDao.save(item155);
		itemDao.save(item156);
		itemDao.save(item157);
		itemDao.save(item158);
		itemDao.save(item159);
		itemDao.save(item160);
		itemDao.save(item161);
		itemDao.save(item162);
		itemDao.save(item163);
		itemDao.save(item164);
		itemDao.save(item165);
		itemDao.save(item166);
		itemDao.save(item167);
		itemDao.save(item168);
		itemDao.save(item169);
		itemDao.save(item170);
		itemDao.save(item171);
		itemDao.save(item172);
		itemDao.save(item173);
		itemDao.save(item174);
		itemDao.save(item175);
		itemDao.save(item176);
		itemDao.save(item177);
		itemDao.save(item178);
		itemDao.save(item179);
		itemDao.save(item180);
		itemDao.save(item181);
		itemDao.save(item182);
		itemDao.save(item183);
		itemDao.save(item184);
		itemDao.save(item185);
		itemDao.save(item186);
		itemDao.save(item187);
		itemDao.save(item188);
		itemDao.save(item189);
		itemDao.save(item190);
		itemDao.save(item191);
		itemDao.save(item192);
		itemDao.save(item193);
		itemDao.save(item194);
		itemDao.save(item195);
		itemDao.save(item196);
		itemDao.save(item197);
		itemDao.save(item198);
		itemDao.save(item199);
		itemDao.save(item200);
		itemDao.save(item201);
		itemDao.save(item202);
		itemDao.save(item203);
		itemDao.save(item204);
		itemDao.save(item205);
		itemDao.save(item206);
		itemDao.save(item207);
		itemDao.save(item208);
		itemDao.save(item209);
		itemDao.save(item210);
		itemDao.save(item211);
		itemDao.save(item212);
		itemDao.save(item213);
		itemDao.save(item214);
		itemDao.save(item215);
		itemDao.save(item216);
		itemDao.save(item217);
		itemDao.save(item218);
		itemDao.save(item219);
		itemDao.save(item220);
		itemDao.save(item221);
		itemDao.save(item222);
		itemDao.save(item223);
		itemDao.save(item224);
		itemDao.save(item225);
		itemDao.save(item226);
		itemDao.save(item227);
		itemDao.save(item228);
		itemDao.save(item229);
		itemDao.save(item230);
		itemDao.save(item231);
		itemDao.save(item232);
		itemDao.save(item233);
		itemDao.save(item234);
		itemDao.save(item235);
		itemDao.save(item236);
		itemDao.save(item237);
		itemDao.save(item238);
		itemDao.save(item239);
		itemDao.save(item240);
		itemDao.save(item241);
		itemDao.save(item242);
		itemDao.save(item243);
		itemDao.save(item244);
		itemDao.save(item245);
		itemDao.save(item246);
		itemDao.save(item247);
		itemDao.save(item248);
		itemDao.save(item249);
		itemDao.save(item250);
		itemDao.save(item251);
		itemDao.save(item252);
		itemDao.save(item253);
		itemDao.save(item254);
		itemDao.save(item255);
		itemDao.save(item256);
		itemDao.save(item257);
		itemDao.save(item258);
		itemDao.save(item259);
		itemDao.save(item260);
		itemDao.save(item261);
		itemDao.save(item262);
		itemDao.save(item263);
		itemDao.save(item264);
		itemDao.save(item265);
		itemDao.save(item266);
		itemDao.save(item267);
		itemDao.save(item268);
		itemDao.save(item269);
		itemDao.save(item270);
		itemDao.save(item271);
		itemDao.save(item272);
		itemDao.save(item273);
		itemDao.save(item274);
		itemDao.save(item275);
		itemDao.save(item276);
		itemDao.save(item277);
		itemDao.save(item278);
		itemDao.save(item279);
		
		
		runeDao.save(rune1);
		runeDao.save(rune2);
		runeDao.save(rune3);
		runeDao.save(rune4);
		runeDao.save(rune5);
		runeDao.save(rune6);
		runeDao.save(rune7);
		runeDao.save(rune8);
		runeDao.save(rune9);
		runeDao.save(rune10);
		runeDao.save(rune11);
		runeDao.save(rune12);
		runeDao.save(rune13);
		runeDao.save(rune14);
		runeDao.save(rune15);
		runeDao.save(rune16);
		runeDao.save(rune17);
		runeDao.save(rune18);
		runeDao.save(rune19);
		runeDao.save(rune20);
		runeDao.save(rune21);
		runeDao.save(rune22);
		runeDao.save(rune23);
		runeDao.save(rune24);
		runeDao.save(rune25);
		runeDao.save(rune26);
		runeDao.save(rune27);
		runeDao.save(rune28);
		runeDao.save(rune29);
		runeDao.save(rune30);
		runeDao.save(rune31);
		runeDao.save(rune32);
		runeDao.save(rune33);
		runeDao.save(rune34);
		runeDao.save(rune35);
		runeDao.save(rune36);
		runeDao.save(rune37);
		runeDao.save(rune38);
		runeDao.save(rune39);
		runeDao.save(rune40);
		runeDao.save(rune41);
		runeDao.save(rune42);
		runeDao.save(rune43);
		runeDao.save(rune44);
		runeDao.save(rune45);
		runeDao.save(rune46);
		runeDao.save(rune47);
		runeDao.save(rune48);
		runeDao.save(rune49);
		runeDao.save(rune50);
		runeDao.save(rune51);
		runeDao.save(rune52);
		runeDao.save(rune53);
		runeDao.save(rune54);
		runeDao.save(rune55);
		runeDao.save(rune56);
		runeDao.save(rune57);
		runeDao.save(rune58);
		runeDao.save(rune59);
		runeDao.save(rune60);
		runeDao.save(rune61);
		runeDao.save(rune62);
		runeDao.save(rune63);
		runeDao.save(rune64);
		runeDao.save(rune65);
		runeDao.save(rune66);
		
		spellDao.save(spell1);
		spellDao.save(spell2);
		spellDao.save(spell3);
		spellDao.save(spell4);
		spellDao.save(spell5);
		spellDao.save(spell6);
		spellDao.save(spell7);
		spellDao.save(spell8);
		spellDao.save(spell9);
		spellDao.save(spell10);
		spellDao.save(spell11);
		spellDao.save(spell12);
		spellDao.save(spell13);
		spellDao.save(spell14);
		spellDao.save(spell15);
		spellDao.save(spell16);
		spellDao.save(spell17);
		spellDao.save(spell18);
		spellDao.save(spell19);

		
		skillDao.save(skill1);
		
		miscDao.save(misc1);
		
		System.out.println("Retrieve all accounts");
		for(Account a : accountDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all champions");
		for(Champion a : championDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all items");
		for(Item a : itemDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all runes");
		for(Rune a : runeDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}

		System.out.println("Retrieve all skills");
		for(Skill a : skillDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all spells");
		for(Spell a : spellDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}
		
		System.out.println("Retrieve all miscellaneous");
		for(Misc a : miscDao.findAll()) {
			System.out.println(a.getNome());
			System.out.println(".-.-.-.");
		}


		
	}
	//prova

}
